'use strict';
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root'),toastEl=document.querySelector('#toast');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),attr=esc;
const asList=(v,...keys)=>Array.isArray(v)?v:(keys.map(k=>v?.[k]).find(Array.isArray)||v?.items||[]);
const pick=(v,keys,f='')=>{const k=keys.find(key=>v?.[key]!==undefined);return k?v[k]:f};
const tokenKey='rebuild_access_token',refreshKey='rebuild_refresh_token',projectKey='rebuild_project_id',allowed=/\.(pdf|docx|xlsx|pptx|md|txt|csv|eml)$/i;
const icons={project:'M3 7h6l2 2h10v11H3z M3 7V4h6l2 3',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',library:'M5 4h14v16H5z M9 8h6 M9 12h6 M9 16h3',data:'M4 5c0-4 16-4 16 0s-16 4-16 0v14c0 4 16 4 16 0V5 M4 12c0 4 16 4 16 0',templates:'M5 3h9l5 5v13H5z M14 3v6h5',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3',upload:'M12 16V3 M7 8l5-5 5 5 M4 15v6h16v-6',plus:'M12 5v14 M5 12h14',file:'M5 3h9l5 5v16H5z M14 3v6h5',arrow:'M5 12h14 M14 7l5 5-5 5',logout:'M10 17l5-5-5-5 M15 12H3 M17 3h4v18h-4',retry:'M20 6v6h-6 M4 18v-6h6'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.file}"/></svg>`;
const menus=[['project','프로젝트','project'],['knowledge','지식조회','search'],['library','지식 자료실','library'],['management','데이터 관리','data'],['templates','표준 양식','templates'],['settings','설정','settings']];
function routeFromHash(){const raw=location.hash.slice(1);if(raw.startsWith('source='))return{page:'project',source:decodeURIComponent(raw.slice(7))};return{page:raw||'project',source:null}}
const initialRoute=routeFromHash();
const state={token:sessionStorage.getItem(tokenKey),refreshToken:sessionStorage.getItem(refreshKey),user:null,page:initialRoute.page,pendingSource:initialRoute.source,projects:[],project:null,mode:'search',searchScope:'all',query:'',result:null,resultContext:null,knowledgeRequestId:0,currentDraft:null,savedDrafts:[],templates:[],draftDirty:false,selectedComparisonId:null,config:null,modalOrigin:null,renderGeneration:0};
class ApiError extends Error{constructor(status,detail){const d=detail?.detail||detail||{};super(typeof d==='string'?d:(d.message||`요청을 완료하지 못했습니다. (HTTP ${status})`));this.status=status;this.code=d.code||`HTTP_${status}`}}
async function refreshSession(){if(!state.refreshToken)return false;const response=await fetch('/api/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.refreshToken})});if(!response.ok)return false;const payload=await response.json(),token=payload.access_token||payload.token||payload.session?.access_token,refresh=payload.refresh_token||payload.session?.refresh_token||state.refreshToken;if(!token)return false;state.token=token;state.refreshToken=refresh;sessionStorage.setItem(tokenKey,token);sessionStorage.setItem(refreshKey,refresh);return true}
async function readErrorPayload(response){const text=await response.text();if(!text)return{};if((response.headers.get('content-type')||'').includes('json')){try{return JSON.parse(text)}catch{return{message:text}}}return{message:text}}
async function authorizedFileResponse(path,options={},retried=false){const headers=new Headers(options.headers||{});if(state.token)headers.set('Authorization',`Bearer ${state.token}`);const response=await fetch(path,{...options,headers});if(response.status===401&&!retried&&await refreshSession())return authorizedFileResponse(path,options,true);if(response.status===401){sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(refreshKey);state.token=null;state.refreshToken=null;renderLogin('세션이 만료되었습니다. 다시 로그인해 주세요.')}return response}
async function api(path,options={},retried=false){
 const headers=new Headers(options.headers||{});if(state.token)headers.set('Authorization',`Bearer ${state.token}`);
 if(options.body&&!(options.body instanceof FormData)&&typeof options.body!=='string'){headers.set('Content-Type','application/json');options.body=JSON.stringify(options.body)}
 const response=await fetch(path,{...options,headers});
 if(response.status===401&&!retried&&!['/api/auth/login','/api/auth/refresh'].includes(path)&&await refreshSession())return api(path,options,true);
 if(response.status===401&&path!=='/api/auth/login'){sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(refreshKey);state.token=null;state.refreshToken=null;renderLogin('세션이 만료되었습니다. 다시 로그인해 주세요.');throw new ApiError(401,{message:'세션 만료'})}
 const type=response.headers.get('content-type')||'',payload=type.includes('json')?await response.json():await response.text();
 if(!response.ok)throw new ApiError(response.status,payload);return payload;
}
async function downloadAuthorized(path,filename,method='GET'){
 const response=await authorizedFileResponse(path,{method});if(!response.ok)throw new ApiError(response.status,await readErrorPayload(response));
 const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;const rawName=response.headers.get('content-disposition')?.match(/filename\*?=(?:UTF-8'')?["']?([^;"']+)/i)?.[1]||'download';try{link.download=filename||decodeURIComponent(rawName)}catch{link.download=filename||rawName}document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),300000);return{url,filename:link.download};
}
async function openAuthorized(path){const viewer=window.open('about:blank','_blank');if(viewer)viewer.opener=null;try{const response=await authorizedFileResponse(path);if(!response.ok)throw new ApiError(response.status,await readErrorPayload(response));const url=URL.createObjectURL(await response.blob());if(viewer)viewer.location.href=url;else{const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.click()}setTimeout(()=>URL.revokeObjectURL(url),120000)}catch(error){viewer?.close();throw error}}
const detailMessage=e=>e instanceof ApiError?`${e.message} [${e.code}]`:(e?.message||'네트워크 연결을 확인한 뒤 다시 시도해 주세요.');
function toast(m){toastEl.textContent=m;toastEl.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.hidden=true,4200)}
const pageHead=(t,d,a='')=>`<header class="page-head"><div><div class="eyebrow">RE:Build Agent · Workspace</div><h1 tabindex="-1">${esc(t)}</h1><p>${esc(d)}</p></div><div class="actions">${a}</div></header>`;
const loading=()=>'<div class="loading" role="status" aria-label="불러오는 중"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>';
const errorView=(e,p=state.page)=>`<div class="notice error" role="alert"><strong>데이터를 불러오지 못했습니다.</strong><br>${esc(detailMessage(e))}<div class="actions" style="margin-top:12px"><button class="btn" data-action="navigate" data-page="${attr(p)}">${icon('retry')} 다시 시도</button></div></div>`;
function knowledgeContext(query=state.query){return{projectId:String(state.project?.id??''),mode:state.mode,query:String(query??''),scope:state.mode==='search'?state.searchScope:'comparison'}}
function knowledgeContextMatches(context){const current=knowledgeContext();return Boolean(context)&&context.projectId===current.projectId&&context.mode===current.mode&&context.query===current.query&&context.scope===current.scope}
function invalidateKnowledgeResults(){state.knowledgeRequestId++;state.result=null;state.resultContext=null}
async function mutateSources(path,options){invalidateKnowledgeResults();try{return await api(path,options)}finally{invalidateKnowledgeResults();state.currentDraft=null;state.draftDirty=false}}
function setKnowledgeProject(project){const changed=String(state.project?.id??'')!==String(project?.id??'');state.project=project;if(changed)invalidateKnowledgeResults()}
function setKnowledgeMode(mode){if(state.mode===mode)return;state.mode=mode;invalidateKnowledgeResults()}
function setKnowledgeScope(scope){if(!['all','current','historical'].includes(scope)||state.searchScope===scope)return;state.searchScope=scope;invalidateKnowledgeResults()}
function setKnowledgeQuery(query){const next=String(query??'');if(state.query===next)return false;state.query=next;invalidateKnowledgeResults();return true}
function currentKnowledgeResult(){return knowledgeContextMatches(state.resultContext)?state.result:null}
async function runKnowledgeQuery(query,region){
 setKnowledgeQuery(String(query??'').trim());const context=knowledgeContext(),requestId=++state.knowledgeRequestId;state.result=null;state.resultContext=null;region.innerHTML=loading();
 try{const payload=context.mode==='search'?await api(`/api/search?q=${encodeURIComponent(context.query)}&project_id=${encodeURIComponent(context.projectId)}&scope=${encodeURIComponent(context.scope)}`):await api(`/api/projects/${encodeURIComponent(context.projectId)}/analyze`,{method:'POST',body:{mode:'ai',question:context.query}});if(requestId!==state.knowledgeRequestId||!knowledgeContextMatches(context))return;state.result=payload;state.resultContext=context;region.innerHTML=resultMarkup(payload)}
 catch(error){if(requestId!==state.knowledgeRequestId||!knowledgeContextMatches(context))return;region.innerHTML=errorView(error,'knowledge')}
}
const empty=(t,b,a='')=>`<section class="empty"><h2>${esc(t)}</h2><p class="muted">${esc(b)}</p>${a}</section>`;
const projectRequired=()=>empty('프로젝트를 먼저 선택하세요','이 기능은 현재 프로젝트의 실제 자료와 연결됩니다.','<button class="btn primary" data-action="navigate" data-page="project">프로젝트로 이동</button>');
function renderLogin(message=''){state.renderGeneration++;app.className='auth-shell';app.setAttribute('aria-busy','false');app.innerHTML=`<main class="auth-card"><div class="brand"><span class="brand-mark">R:</span><span>RE:Build Agent</span></div><h1>워크스페이스 로그인</h1><p class="muted">승인된 프로젝트와 원문에 접근하려면 로그인하세요.</p>${message?`<div class="notice error form-error" tabindex="-1">${esc(message)}</div>`:''}<form id="login-form"><label for="email">이메일</label><input id="email" name="email" type="email" autocomplete="username" required><label for="password">비밀번호</label><input id="password" name="password" type="password" autocomplete="current-password" required><div id="login-error" class="field-error" role="alert"></div><button class="btn primary" type="submit" style="width:100%;margin-top:20px">로그인</button></form><p class="helper small" style="margin-top:18px">기본 로그인은 Supabase Auth 세션을 사용합니다. 사내 SSO는 설정 전까지 사용할 수 없습니다.</p></main>`}
function shell(){app.className='app-shell';const label=menus.find(x=>x[0]===state.page)?.[1]||'프로젝트';app.innerHTML=`<div class="app-layout"><aside class="sidebar"><div class="brand"><span class="brand-mark">R:</span><span>RE:Build Agent</span></div><div class="nav-label">WORKSPACE</div><nav class="main-nav" aria-label="주 메뉴">${menus.map(([id,l,g])=>`<button class="nav-button" data-action="navigate" data-page="${id}" aria-current="${state.page===id?'page':'false'}">${icon(g)}<span>${l}</span></button>`).join('')}</nav><div class="side-project"><span class="eyebrow">CURRENT PROJECT</span><strong>${esc(state.project?.name||'프로젝트 선택 전')}</strong><p class="small muted">${state.project?'자료에서 검토까지 이어가기':'새 프로젝트를 만들거나<br>기존 프로젝트를 여세요.'}</p></div><div class="side-bottom"><span class="avatar">R:</span><span>프로젝트 워크스페이스<br>근거로 이어지는 경험</span></div></aside><section class="workspace"><header class="topbar"><div class="topbar-meta"><span>워크스페이스</span><span aria-hidden="true">/</span><strong>${label}</strong></div><div class="user-menu"><span>${esc(state.user?.email||state.user?.name||'사용자')}</span><button class="btn ghost" data-action="logout">${icon('logout')} 로그아웃</button></div></header><main class="main" id="main" tabindex="-1">${loading()}</main></section></div>`}
function setMain(html,generation){if(generation!==state.renderGeneration)return false;const main=document.querySelector('#main');if(!main)return false;main.innerHTML=html;app.setAttribute('aria-busy','false');return true}
async function initialize(){if(!state.token)return renderLogin();const generation=++state.renderGeneration;try{const [me,config]=await Promise.all([api('/api/auth/me'),api('/api/config')]);if(generation!==state.renderGeneration)return;state.user=me.user||me;state.config=config;shell();await loadProjects();if(generation!==state.renderGeneration)return;await renderPage(generation);if(generation===state.renderGeneration&&state.pendingSource)await openSourcePanel(state.pendingSource,generation)}catch(e){if(generation===state.renderGeneration&&e.status!==401)renderLogin(detailMessage(e))}}
async function loadProjects(){const p=await api('/api/projects');state.projects=asList(p,'projects');const selected=sessionStorage.getItem(projectKey);setKnowledgeProject(state.projects.find(x=>String(x.id)===selected)||null)}
async function navigate(page){if(!menus.some(x=>x[0]===page))page='project';const generation=++state.renderGeneration;state.page=page;location.hash=page;shell();try{await renderPage(generation)}catch(e){setMain(errorView(e,page),generation)}}
async function renderPage(generation){const page=state.page;await ({project:renderProjects,knowledge:renderKnowledge,library:renderLibrary,management:renderManagement,templates:renderTemplates,settings:renderSettings}[page])(generation)}

function draftHistoryMarkup(kind){const saved=state.savedDrafts.filter(d=>(d.kind||d.output_kind||d.type)===kind);return saved.length?`<div class="stack">${saved.map(d=>`<button class="btn" data-action="open-draft" data-id="${attr(d.id)}"><span>Rev ${esc(d.revision??'미확정')} · ${esc(d.status||'draft')}</span></button>`).join('')}</div>`:'<p class="small muted">저장된 초안 없음</p>'}
function applyDraftResponse(payload,projectId,generation){if(state.page!=='project'||state.project?.id!==projectId||state.renderGeneration!==generation)return false;const draft=payload.draft||payload;if(draft.project_id&&draft.project_id!==projectId)return false;state.currentDraft=draft;state.draftDirty=false;state.savedDrafts=[draft,...state.savedDrafts.filter(d=>d.id!==draft.id)];const region=document.querySelector('#draft-region');if(region)region.innerHTML=draftMarkup(draft);const kind=draft.kind||draft.output_kind||draft.type,history=document.querySelector(`.saved-draft-list[data-output-kind="${kind}"]`);if(history)history.innerHTML=draftHistoryMarkup(kind);return true}
async function renderProjects(generation){
 if(!state.project){await loadProjects();setMain(pageHead('프로젝트','새로운 프로젝트에, 축적된 경험을 연결하세요.','<button class="btn primary" data-action="new-project">'+icon('plus')+' 새 프로젝트</button>')+`<section class="intro"><div class="eyebrow">FROM EXPERIENCE TO EVIDENCE</div><h2>과거의 경험을 연결하고,<br>새로운 프로젝트의 판단을 완성하세요.</h2><p>프로젝트 자료를 추가하면 원문을 보존하고, 과거 근거와 비교해 검토할 결과물을 만듭니다.</p><button class="btn primary" data-action="new-project">${icon('plus')} 프로젝트 시작하기</button><div class="flow"><span>원본 보존</span><span>지식화</span><span>근거 검토</span><span>검토·승인</span><span>파일 생성</span></div></section><div class="section-title"><h2>프로젝트 워크스페이스</h2><span class="small muted">등록 프로젝트 ${state.projects.length}개</span></div><div class="project-list">${state.projects.map(p=>`<article class="project-row"><div class="row between"><span class="project-badge">${icon('project')}</span><span class="tag ${p.kind==='current'?'green':''}">${esc(p.kind==='historical'?'과거 프로젝트':'검토 프로젝트')}</span></div><h3>${esc(p.name)}</h3><p class="small muted">${p.kind==='historical'?'경험과 원문 근거를 축적하는 자료':'신규 조건을 비교하고 업무 결과물을 검토'}</p><div class="project-meta"><span>생성 ${esc(p.created_at?new Date(p.created_at).toLocaleDateString('ko-KR'):'시각 미제공')}</span><div class="actions"><button class="link-button" data-action="manage-project" data-id="${attr(p.id)}" aria-label="${attr(p.name)} 관리">관리</button><button class="btn" data-action="open-project" data-id="${attr(p.id)}">열기 ${icon('arrow')}</button></div></div></article>`).join('')}<button class="project-row new-project-card" data-action="new-project">${icon('plus')}<strong>새 프로젝트 만들기</strong><span class="small muted">이름과 원본 자료로 시작하세요.</span></button></div>`,generation);return}
 const projectId=state.project.id;const [project,docsPayload,draftsPayload,templatePayload]=await Promise.all([api(`/api/projects/${encodeURIComponent(state.project.id)}`),api(`/api/projects/${encodeURIComponent(state.project.id)}/documents`),api(`/api/projects/${encodeURIComponent(state.project.id)}/drafts`),api('/api/templates')]);if(generation!==state.renderGeneration||state.page!=='project'||state.project?.id!==projectId)return;setKnowledgeProject(project.project||project);const docs=asList(docsPayload,'documents');state.savedDrafts=asList(draftsPayload,'drafts');state.templates=asList(templatePayload,'templates');const retryableStatuses=new Set(['ERROR','OCR_REQUIRED','UNSUPPORTED','FAILED']);
 const outputs=[['itb','ITB 분석표','입찰 조건과 과거 이슈를 근거와 함께 검토합니다.'],['slides','심의장표','실제 5장 구성으로 의사결정을 정리합니다.'],['risk','Risk Register','근거 있는 위험과 대응방안을 구분합니다.']];
 setMain(pageHead(state.project.name,'원본 자료, 초안, 검토와 최종 승인을 한 흐름에서 관리합니다.',`<button class="btn" data-action="switch-project">프로젝트 변경</button><button class="btn" data-action="manage-project" data-id="${attr(state.project.id)}">프로젝트 관리</button><button class="btn primary" data-action="upload">${icon('upload')} 파일 추가</button>`)+
 `<div class="intake-bar">${icon('project')}<div class="grow"><h3>프로젝트 자료 <span class="tag">${docs.length}개</span></h3><p class="small muted">실제 등록 원본 · 입력 변경 시 기존 결과물 승인은 무효화됩니다.</p></div><div class="flow"><span>원본 보존</span><span>지식화</span><span>근거 연결</span></div></div>
 <section class="card"><div class="row between"><div><h2>프로젝트 자료</h2><p class="muted small">입력 변경 시 기존 결과물 승인은 무효화됩니다.</p></div></div>${docs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>문서</th><th>개정</th><th>등록 승인</th><th>추출 상태</th><th>원문·재처리</th></tr></thead><tbody>${docs.map(d=>{const status=String(d.extraction_status||'').toUpperCase();return`<tr><td>${esc(d.filename)}</td><td>${esc(d.revision||'미확정')}</td><td>${esc(d.approval_status||'미확정')}</td><td><span class="tag ${status==='REVIEW_REQUIRED'||retryableStatuses.has(status)?'amber':''}">${esc(d.extraction_status||'미확정')}</span></td><td><div class="actions"><button class="link-button" data-action="original" data-id="${attr(d.id)}" data-name="${attr(d.filename)}">원문 열기</button>${retryableStatuses.has(status)?`<button class="btn" data-action="retry-document" data-id="${attr(d.id)}">${icon('retry')} 재처리</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted">등록된 문서가 없습니다. 파일을 추가해 시작하세요.</p>'}</section>
 <div class="grid-3 output-cards" style="margin-top:20px">${outputs.map(([kind,title,body])=>{const saved=state.savedDrafts.filter(d=>(d.kind||d.output_kind||d.type)===kind);return`<article class="card template-card output-card"><div class="row between"><span class="project-badge">${icon('file')}</span><span class="tag">${kind==='slides'?'PPTX · 5장':'XLSX'}</span></div><span class="eyebrow">초안 → 근거 → 검토 → 승인</span><h2 style="margin-top:16px">${title}</h2><p class="muted">${body}</p><div class="saved-draft-list" data-output-kind="${kind}">${draftHistoryMarkup(kind)}</div><div class="template-actions"><button class="btn primary" data-action="new-draft" data-kind="${kind}">새 초안 만들기</button></div></article>`}).join('')}</div><section id="draft-region" style="margin-top:20px">${state.currentDraft?draftMarkup(state.currentDraft):''}</section>`,generation);
}
const draftTitle=k=>({itb:'ITB 분석표',risk:'Risk Register',slides:'심의장표'}[k]||k||'초안');
function refsMarkup(refs){return refs.length?refs.map(r=>`<button type="button" class="link-button" data-action="source-original" data-id="${attr(pick(r,['document_id','documentId','id']))}" data-name="${attr(r.filename||'원문')}">${esc(r.filename||r.document_id||'원문')}<br><span class="small muted">${esc(r.locator||'위치 미제공')}</span></button>`).join(''):'<span class="tag amber">REVIEW_REQUIRED</span>'}
function uniqueDraftRefs(refs){const seen=new Set();return refs.filter(ref=>{const key=JSON.stringify(ref);if(seen.has(key))return false;seen.add(key);return true})}
function draftRefsButton(refs,index){const count=uniqueDraftRefs(refs).length;return count?`<button type="button" class="btn draft-evidence-button" data-action="draft-evidence" data-row-index="${index}" aria-label="${index+1}번 항목 근거 ${count}개 보기"><strong>근거 ${count}개</strong><span>보기 ↗</span></button>`:'<span class="tag amber">검토 필요</span><p class="small muted">연결된 근거 없음</p>'}
function draftEvidenceMarkup(row){const used=new Set(),groups=[['신규 프로젝트 근거',asList(row.current_refs)],['과거 프로젝트 근거',asList(row.historical_refs)],['추가 연결 근거',asList(row.source_refs)]];return `<p class="muted">${esc(row.title||'선택 항목')} · 문서명과 원문 위치를 확인한 뒤 원본을 열어 검토하세요.</p><div class="draft-evidence-list">${groups.map(([title,refs])=>{const unique=refs.filter(ref=>{const key=JSON.stringify(ref);if(used.has(key))return false;used.add(key);return true});return unique.length?`<section><h3>${title} · ${unique.length}개</h3><div class="draft-evidence-links">${refsMarkup(unique)}</div></section>`:''}).join('')}</div>`}
function draftRow(row,index,kind){const refs=[...asList(row.source_refs),...asList(row.current_refs),...asList(row.historical_refs)],field=(name,value,label)=>`<textarea name="${name}" aria-label="${index+1}번 ${label}">${esc(Array.isArray(value)?value.join("\n"):value)}</textarea>`;if(kind==='slides')return`<tr data-row="${index}"><td><input name="title" value="${attr(row.title)}" aria-label="${index+1}번 슬라이드 제목"></td><td>${field('current',row.current||row.rationale,'슬라이드 핵심 내용')}${row.detail_text?`<details><summary>전체 비교 내용 · 발표자 노트</summary><p class="small muted">화면의 짧은 발췌와 별도로 전체 비교 내용과 모든 원문 근거를 PPTX 발표자 노트에 보존합니다.</p><pre style="white-space:pre-wrap">${esc(row.detail_text)}</pre></details>`:''}</td><td>${field('decision',row.decision||row.missing_information,'슬라이드 결정 사항')}${field('rationale',row.rationale,'슬라이드 검토 의견')}</td><td>${draftRefsButton(refs,index)}</td></tr>`;if(kind==='risk')return`<tr data-row="${index}"><td><input name="title" value="${attr(row.title)}" aria-label="${index+1}번 위험"></td><td>${field('current',row.current,'조건')}</td><td>${field('severity',row.severity,'강도')}</td><td>${field('past',row.past,'과거 프로젝트')}</td><td>${field('mitigation',row.mitigation,'대응')}</td><td>${draftRefsButton(refs,index)}</td></tr>`;return`<tr data-row="${index}"><td><input name="title" value="${attr(row.title)}" aria-label="${index+1}번 항목"></td><td>${field('current',row.current,'현재 조건')}</td><td>${field('past',row.past,'과거 근거')}</td><td>${field('differences',row.differences,'차이')}</td><td>${field('decision',row.decision,'판단')}</td><td>${field('rationale',row.rationale,'판단 근거')}</td><td>${field('missing_information',row.missing_information,'미확정 정보')}</td><td>${draftRefsButton(refs,index)}</td></tr>`}
function draftMarkup(draft){const rows=asList(draft.rows),kind=draft.kind||draft.output_kind||draft.type,approved=draft.status==='approved',dirty=state.draftDirty,heads=kind==='slides'?['슬라이드','핵심 내용','결정/검토']:kind==='risk'?['위험','조건','강도','과거 프로젝트','대응']:['항목','현재 조건','과거 근거','차이','판단','판단 근거','미확정 정보'],template=state.templates.find(t=>String(t.id)===String(draft.template_id)),versions=asList(template,'versions'),selectedVersion=draft.template_version||draft.template_sha256||template?.sha256,knownVersions=versions.some(v=>String(v.version||v.sha256)===String(selectedVersion))?versions:[...(selectedVersion?[{version:selectedVersion,sha256:selectedVersion,filename:template?.filename||draft.title,origin:'draft'}]:[]),...versions];return`<section class="card"><div class="row between"><div><span class="tag ${dirty||!approved?'amber':'green'}">${dirty?'저장되지 않은 변경':approved?'최종 승인':'검토 중'}</span><h2 style="margin-top:12px">${esc(draftTitle(kind))} · Rev ${esc(draft.revision??'미확정')}</h2></div><div class="actions"><button class="btn" data-action="save-draft">${approved?'새 개정 저장':'수정 저장'}</button><button class="btn primary" data-action="approve-draft" ${approved||dirty?'disabled':''}>검토 후 승인</button><button class="btn" data-action="export-draft" ${!approved||dirty?'disabled':''}>실제 파일 내보내기</button></div></div><p class="notice ${approved&&!dirty?'':'review'}">${dirty?'변경 내용을 저장해야 승인 또는 내보내기를 할 수 있습니다.':approved?'현재 입력·양식·근거 버전에 승인된 결과입니다.':'미확정 값과 REVIEW_REQUIRED 항목을 확인하고 검토 의견을 저장하세요.'}</p>${kind==='slides'?'<p class="notice">심의장표는 원문 발췌로 만든 편집 가능한 5장 초안입니다. 전체 비교와 원문 근거는 아래 펼침 영역과 PPTX 발표자 노트에서 확인하세요. 본문·결정·검토 의견이 한 장의 표시 한도를 넘으면 저장·승인이 제한됩니다.</p>':''}${kind==='slides'&&rows.length!==5?'<p class="notice review">심의장표는 5장이어야 합니다. 현재 서버 응답을 검토하세요.</p>':''}<div id="download-status" class="download-status" role="status" aria-live="polite"></div><form id="draft-form"><label for="draft-bound-version">결과물 양식 버전<select id="draft-bound-version" name="template_version">${knownVersions.map(v=>{const hash=v.version||v.sha256;return`<option value="${attr(hash)}" ${String(hash)===String(selectedVersion)?'selected':''}>${esc(v.filename||template?.filename||'양식')} · ${esc(v.origin||'출처 미제공')} · ${esc(hash)}</option>`}).join('')}</select></label><p class="small muted">선택된 SHA-256: ${esc(selectedVersion||'미제공')}. 버전을 변경해 저장하면 기존 최종 승인은 무효화됩니다.</p><p class="small muted">근거는 각 행의 보기 버튼에서 확인합니다. 넓은 표는 좌우로 스크롤할 수 있습니다.</p><div class="table-wrap draft-table-wrap" role="region" aria-label="초안 검토 표" tabindex="0"><table class="table draft-table draft-table-${attr(kind)}"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}<th>근거</th></tr></thead><tbody>${rows.length?rows.map((r,i)=>draftRow(r,i,kind)).join(''):`<tr><td colspan="${heads.length+1}">서버가 생성한 행이 없습니다. 입력 문서와 분석 상태를 확인하세요.</td></tr>`}</tbody></table></div></form></section>`}

function projectAIConnection(status,selection){if(!selection)return{connected:false,message:'프로젝트의 AI 구성 상태를 확인하지 못했습니다. 설정을 다시 확인하세요.'};if(selection.selected_profile)return{connected:false,message:selection.selected_profile.name+' · NOT_CONFIGURED. 선택된 사내 LLM은 아직 연결되지 않았으며 기본 OpenAI로 자동 전환하지 않습니다.'};return{...status,connected:Boolean(status.connected&&status.inference==='SUCCEEDED')}}
async function renderKnowledge(generation){
 if(!state.project)return setMain(pageHead('지식조회','')+projectRequired(),generation);
 let provider={connected:false};if(state.mode==='ai'){try{const [status,selection]=await Promise.all([api('/api/provider/status'),api('/api/projects/'+encodeURIComponent(state.project.id)+'/provider')]);provider=projectAIConnection(status,selection)}catch(e){provider={connected:false,error:detailMessage(e)}}}const connected=Boolean(provider.connected);
 const result=currentKnowledgeResult();
 setMain(pageHead('지식조회','')+`<div class="tabs" role="tablist" aria-label="지식조회 모드"><button class="tab" role="tab" aria-selected="${state.mode==='search'}" data-action="mode" data-mode="search">Search Mode</button><button class="tab" role="tab" aria-selected="${state.mode==='ai'}" data-action="mode" data-mode="ai">AI Insight Mode</button></div>${state.mode==='ai'&&!connected?`<div class="notice review"><strong>AI 연결 미확인</strong><br>${esc(provider.message||provider.error||'모델 호출 성공이 검증되지 않았습니다. 설정에서 연결 시험을 완료하세요.')}</div>`:''}<form id="query-form" class="query-form" style="margin-top:16px">${state.mode==='search'?`<label for="search-scope">검색 자료 범위</label><select id="search-scope" name="scope">${[['all','전체 자료'],['current','현재 프로젝트'],['historical','과거 프로젝트']].map(([value,label])=>`<option value="${value}" ${state.searchScope===value?'selected':''}>${label}</option>`).join('')}</select>`:''}<label for="query">질문 또는 확인할 조건</label><div class="query-box"><input id="query" name="query" value="${attr(state.query)}" placeholder="실제 프로젝트 자료에서 확인할 내용을 입력하세요" required><button class="btn primary" type="submit">${state.mode==='search'?'자료 검색':'적용 검토 실행'}</button></div></form><section id="query-results" style="margin-top:20px">${result?resultMarkup(result):empty('질문을 입력하세요','')}</section>`,generation);
}
function resultMarkup(payload){
 const ai=payload.mode==='ai'||Boolean(payload.ai_insight),insight=payload.ai_insight||{},answer=payload.answer||insight.answer||'',all=asList(payload,'results','matches','rows','insights'),results=ai?all.filter(item=>item.method==='AI_INFERENCE'):all;
 const evidence=item=>uniqueDraftRefs([...asList(item.source_refs),...asList(item.current_refs),...asList(item.historical_refs),...(item.source_ref?[item.source_ref]:[])]),paragraphs=text=>String(text||'').split(/\n\s*\n/).filter(Boolean).map(part=>`<p>${esc(part)}</p>`).join('');
 const cards=results.map((item,index)=>{const refs=evidence(item),source=item.source_ref||refs[0],title=ai?`검토 근거 ${index+1}`:item.title||item.filename||source?.filename||'원문 검색 결과';return `<article class="card knowledge-result"><div class="row between"><h3>${esc(title)}</h3><span class="tag ${ai?'amber':''}">${ai?'AI 해석 · 검토 필요':'원문 발췌'}</span></div><div class="result-text">${paragraphs(item.text||item.summary||item.rationale||'')}</div>${refs.length?`<details class="result-evidence"><summary>근거 보기</summary>${!ai&&item.reason?`<p class="small muted">${esc(item.reason)}</p>`:''}${refsMarkup(refs)}</details>`:'<p class="small muted">연결된 원문 근거가 없습니다. 검토가 필요합니다.</p>'}</article>`}).join('');
 return `${ai?`<section class="card insight-answer"><div class="row between"><h2>질문에 대한 적용 검토</h2><span class="tag amber">AI Insight · 검토 필요</span></div><div class="result-text">${answer?paragraphs(answer):'<p>AI 답변이 제공되지 않았습니다. 연결 상태와 입력 근거를 확인하세요.</p>'}</div></section>`:`<div class="row between result-summary"><h2>관련 원문 ${results.length}건</h2><span class="small muted">키워드 검색</span></div>`}<div class="stack">${cards||empty(ai?'연결된 검토 근거가 없습니다':'검색된 자료가 없습니다',ai?'답변의 적용 여부는 원문 확인 후 검토하세요.':'검색 범위를 전체 자료로 바꾸거나 계약 조건·공기 등 핵심 용어로 검색해 보세요.')}</div>`;
}
function graphRelationsMarkup(comparisons){return `<div class="graph-labels"><span>과거 프로젝트 · 원문</span><span>연결된 지식 항목</span><span>신규 프로젝트 · 원문</span></div><div class="graph-relations">${comparisons.map(row=>{const past=asList(row.historical_refs)[0],current=asList(row.current_refs)[0];const node=(ref,emptyText)=>ref?`<button class="node" data-action="graph-document" data-id="${attr(ref.document_id)}"><small>${esc(ref.locator||'원문 위치 확인')}</small><strong>${esc(ref.filename||'원문 문서')}</strong></button>`:`<div class="node unlinked"><small>연결 근거 미확인</small><strong>${emptyText}</strong></div>`;return `<div class="graph-row ${past?'':'no-past'} ${current?'':'no-current'} ${String(row.id)===String(state.selectedComparisonId)?'selected':''}">${past||current?`<svg class="graph-connectors" viewBox="0 0 100 2" preserveAspectRatio="none" aria-hidden="true">${past?'<line x1="16.67" y1="1" x2="50" y2="1"/>':''}${current?'<line x1="50" y1="1" x2="83.33" y2="1"/>':''}</svg>`:''}${node(past,'과거 근거 검토 필요')}<button class="node condition" data-action="select-comparison" data-row-id="${attr(row.id)}"><strong>${esc(row.title)}</strong><small>${esc(row.decision||'REVIEW_REQUIRED')}</small></button>${node(current,'신규 조건 검토 필요')}</div>`}).join('')}</div>`}
async function renderLibrary(generation){if(!state.project)return setMain(pageHead('지식 자료실','실제 프로젝트·문서·근거 사이의 연결과 과거↔신규 비교를 확인합니다.')+projectRequired(),generation);const p=await api(`/api/projects/${encodeURIComponent(state.project.id)}/knowledge`),nodes=asList(p,'nodes'),edges=asList(p,'edges'),comparisons=asList(p,'comparisons'),selected=comparisons.find(row=>String(row.id)===String(state.selectedComparisonId))||comparisons[0],nodeNames=new Map(nodes.map(node=>[node.id,node.label||node.id]));setMain(pageHead('지식 자료실','실제 노드와 근거 edge, 과거↔신규 비교, 양쪽 원문을 한 화면에서 확인합니다.')+`<section class="card graph-card"><div class="row between graph-head"><div><h2>기본 지식 연결</h2><p class="small muted">거리와 선 굵기는 점수나 위험도를 뜻하지 않습니다.</p></div><span class="tag">${nodes.length}개 노드 · ${edges.length}개 연결</span></div>${nodes.length?`${graphRelationsMarkup(comparisons)}<details class="graph-inventory" open><summary>전체 프로젝트·문서 노드 확인 · ${nodes.filter(node=>node.type!=='knowledge').length}개</summary><div class="graph-nodes">${nodes.filter(node=>node.type!=='knowledge').map(node=>node.type==='knowledge'?`<button class="node" data-action="select-comparison" data-row-id="${attr(node.row_id)}"><span class="eyebrow">KNOWLEDGE</span><strong style="display:block;margin:8px 0">${esc(node.label)}</strong><span class="small muted">비교 항목 열기</span></button>`:node.type==='document'?`<button class="node" data-action="graph-document" data-id="${attr(node.document_id)}"><span class="eyebrow">DOCUMENT</span><strong style="display:block;margin:8px 0">${esc(node.label)}</strong><span class="small muted">${esc(node.source_ref?.locator||'원문 위치 확인')}</span></button>`:`<article class="node"><span class="eyebrow">PROJECT</span><strong style="display:block;margin:8px 0">${esc(node.label)}</strong></article>`).join('')}</div></details><details class="graph-inventory"><summary>전체 연결 근거 · ${edges.length}개</summary><div class="stack" style="margin-top:18px">${edges.map(edge=>`<div class="source-ref"><strong>${esc(nodeNames.get(edge.source)||edge.source)} → ${esc(nodeNames.get(edge.target)||edge.target)}</strong><span class="small muted">${esc(edge.label||edge.type)}</span>${edge.source_ref?`<button class="link-button" data-action="graph-document" data-id="${attr(edge.source_ref.document_id)}">연결 원문 · ${esc(edge.source_ref.locator||'위치 확인')}</button>`:''}</div>`).join('')}</div></details>`:empty('연결이 없습니다','현재 프로젝트에서 생성된 지식 연결이 없습니다.')}</section><section style="margin-top:26px"><div class="section-title"><h2>지식의 연결 · 과거 ↔ 신규</h2><span class="small muted">위 노드를 선택해 연결 이유를 확인하세요</span></div>${selected?comparisonMarkup(selected):empty('비교가 없습니다','과거 자료와 신규 자료 사이에 확인된 비교가 없습니다.')}</section>`,generation)}
function comparisonMarkup(item){const pastValue=item.past??item.historical??{},currentValue=item.current??item.new??{},pastObject=typeof pastValue==='object'&&pastValue!==null?pastValue:{},currentObject=typeof currentValue==='object'&&currentValue!==null?currentValue:{},pastText=typeof pastValue==='string'?pastValue:(pastObject.text||pastObject.summary||''),currentText=typeof currentValue==='string'?currentValue:(currentObject.text||currentObject.summary||''),pastRefs=asList(item.historical_refs).length?asList(item.historical_refs):(asList(pastObject.source_refs).length?asList(pastObject.source_refs):(pastObject.source_ref?[pastObject.source_ref]:[])),currentRefs=asList(item.current_refs).length?asList(item.current_refs):(asList(currentObject.source_refs).length?asList(currentObject.source_refs):(currentObject.source_ref?[currentObject.source_ref]:[])),decision=item.decision||'REVIEW_REQUIRED',missing=Array.isArray(item.missing_information)?item.missing_information:[item.missing_information].filter(Boolean),differences=Array.isArray(item.differences)?item.differences:[item.differences].filter(Boolean);return`<article class="card"><div class="row between"><div><span class="tag ${decision==='REFERENCE'?'green':'amber'}">${esc(decision)}</span><h2 style="margin-top:12px">${esc(item.title||'과거↔신규 비교')}</h2></div></div><div class="comparison"><div class="comparison-side"><span class="eyebrow">PAST</span><h3>${esc(pastObject.title||pastObject.project||'과거 프로젝트 근거')}</h3><p>${esc(pastText)}</p>${pastRefs.length?`<details class="comparison-evidence"><summary>과거 원문 근거 ${uniqueDraftRefs(pastRefs).length}개 보기</summary>${refsMarkup(pastRefs)}</details>`:''}</div><div class="comparison-link" aria-label="과거 자료와 신규 자료 연결">↔</div><div class="comparison-side"><span class="eyebrow">CURRENT</span><h3>${esc(currentObject.title||currentObject.project||'신규 프로젝트 조건')}</h3><p>${esc(currentText)}</p>${currentRefs.length?`<details class="comparison-evidence"><summary>신규 원문 근거 ${uniqueDraftRefs(currentRefs).length}개 보기</summary>${refsMarkup(currentRefs)}</details>`:''}</div></div><div style="margin-top:20px"><h3>차이</h3><p>${esc(differences.join(' · ')||'원문 조건을 나란히 검토하세요.')}</p><h3>연결 이유</h3><p>${esc(item.rationale||'근거 연결 설명 미제공')}</p><h3>미확정 정보와 다음 검토</h3><p>${esc(missing.join(' · ')||'추가 미확정 정보 없음')}</p></div></article>`}
async function renderManagement(generation){const [data,templatePayload]=await Promise.all([api('/api/management'),api('/api/templates')]),recent=asList(data,'new_documents','recent_documents'),docs=asList(data,'documents'),rawProjects=asList(data,'projects'),projects=rawProjects.length?rawProjects:state.projects.map(p=>{const owned=docs.filter(d=>String(d.project_id)===String(p.id));return{...p,document_count:owned.length,file_types:[...new Set(owned.map(d=>(d.filename||'').split('.').pop()?.toUpperCase()).filter(Boolean))]}}),counts=data.counts||data,newCount=counts.new_document_count??(Array.isArray(counts.new_documents)?counts.new_documents.length:(counts.new_documents??recent.length)),templateCount=counts.templates??counts.template_count??asList(templatePayload,'templates').length;setMain(pageHead('데이터 관리','과거 프로젝트·문서 보유량과 새로 유입된 문서를 실제 등록 데이터로 확인합니다.',`<span class="tag ${data.up_to_date?'green':'amber'}">${data.up_to_date?'최신 상태':'확인 필요'}</span><span class="small muted">${esc(data.checked_at||'확인 시각 미제공')}</span><button class="btn primary" data-action="folder-candidates">${icon('upload')} 폴더 자료 확인</button>`)+`<div class="stats"><div class="card stat"><span class="muted">과거 프로젝트</span><strong>${esc(counts.historical_projects??counts.project_count??0)}</strong><span class="small muted">접근 가능한 프로젝트</span></div><div class="card stat"><span class="muted">과거 보유 문서</span><strong>${esc(counts.historical_documents??counts.document_count??0)}</strong><span class="small muted">실제 등록 원본</span></div><div class="card stat"><span class="muted">새로 유입된 문서</span><strong>${esc(newCount)}</strong><span class="small muted">신규 자료</span></div><div class="card stat"><span class="muted">공통 표준 양식</span><strong>${esc(templateCount)}</strong><span class="small muted">원본 제공 양식</span></div></div><div class="grid-2"><section class="card"><h2>프로젝트별 문서</h2>${projects.length?`<div class="table-wrap"><table class="table"><thead><tr><th>프로젝트</th><th>문서 수</th><th>구성</th></tr></thead><tbody>${projects.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.document_count??p.count??0)}</td><td>${esc((p.file_types||p.types||[]).join?.(' · ')||p.file_types||'')}</td></tr>`).join('')}</tbody></table></div>`:empty('집계가 없습니다','접근 가능한 프로젝트 데이터가 없습니다.')}</section><section class="card"><h2>새로 유입된 문서</h2>${recent.length?`<div class="stack">${recent.map(d=>`<div class="source-ref"><strong>${esc(d.filename||d.name)}</strong><span class="small muted">${esc(d.project_name||state.projects.find(p=>String(p.id)===String(d.project_id))?.name||'')} · ${esc(d.created_at||d.received_at||'')}</span></div>`).join('')}</div>`:empty('새 문서가 없습니다','현재 조회 범위에 새로 유입된 문서가 없습니다.')}</section></div>`,generation)}
async function renderTemplates(generation){const templates=asList(await api('/api/templates'),'templates');state.templates=templates;setMain(pageHead('표준 양식','제공된 실제 7종과 등록된 불변 버전을 확인하고 인증된 경로로 내려받습니다.')+`<p class="small muted">제공 원본 양식 폴더</p><div class="template-path">data/REBUILD_INPUT_v1/REBUILD_INPUT_v1/03_OUTPUT_TEMPLATES</div>`+(templates.length?`<div class="grid-3 template-grid">${templates.map(t=>{const versions=asList(t,'versions'),ext='.'+String(t.filename||t.name||'').split('.').pop().toLowerCase();return`<article class="card template-card"><div class="template-art" aria-hidden="true"><div class="template-sheet">${'<span></span>'.repeat(6)}</div></div><span class="tag">${esc(ext.slice(1).toUpperCase())}</span><h2 style="margin-top:16px">${esc(t.label||t.title||t.filename||t.name)}</h2><p class="muted">${esc(t.description||'설명 미제공')}</p><p class="small muted">${esc(t.filename||t.name)} · 제공 SHA-256 ${esc(t.sha256||'미제공')}</p><div class="stack">${versions.map(v=>`<div class="source-ref"><strong>${esc(v.filename||t.filename||t.name)}</strong><span class="small muted">${esc(v.origin||'출처 미제공')} · ${esc(v.created_at||'제공 원본')}</span><code>${esc(v.version||v.sha256||'해시 미제공')}</code><button class="link-button" data-action="template-original" data-id="${attr(t.id)}" data-version="${attr(v.version||v.sha256)}" data-name="${attr(v.filename||t.filename||t.name)}">이 버전 다운로드</button></div>`).join('')}</div><form class="template-version-form" data-template-id="${attr(t.id)}"><label>새 버전 등록<input type="file" name="file" accept="${attr(ext)}" required></label><p class="helper small">등록 후 기존 승인 결과물의 양식은 자동으로 바뀌지 않습니다.</p>${t.id==='slides'?'<p class="helper small">심의장표는 제공 원본의 가로형 슬라이드 크기·5장 구성·입력 영역을 유지해야 합니다.</p>':''}<button class="btn" type="submit">검증 후 버전 등록</button></form></article>`}).join('')}</div>`:empty('양식이 없습니다','서버에서 사용 가능한 양식을 반환하지 않았습니다.')),generation)}
function profileFields(profile={type:'corporate_llm'}){const sso=profile.type==='sso',protocols=sso?['OIDC','SAML']:['OpenAI-compatible HTTPS','Azure OpenAI HTTPS'];return `<input type="hidden" name="type" value="${attr(profile.type)}"><label>표시 이름<input name="name" value="${attr(profile.name||'')}" required></label><label>Protocol<select name="protocol">${protocols.map(value=>`<option ${profile.protocol===value?'selected':''}>${value}</option>`).join('')}</select></label><label>HTTPS Endpoint<input name="endpoint" type="url" value="${attr(profile.endpoint||'')}" placeholder="https://service.company.example" required></label>${sso?'<input type="hidden" name="model" value="">':`<label>모델<input name="model" value="${attr(profile.model||'')}"></label>`}`}
async function renderSettings(generation){
 const [status,config,profilesPayload,projectsPayload]=await Promise.all([api('/api/provider/status'),api('/api/config'),api('/api/settings/profiles'),api('/api/projects')]);
 const profiles=asList(profilesPayload),projects=asList(projectsPayload),targetId=state.settingsProjectId||state.project?.id||projects[0]?.id,target=projects.find(p=>p.id===targetId);
 const selection=target?await api('/api/projects/'+encodeURIComponent(target.id)+'/provider'):null,connected=Boolean(status.connected&&status.inference==='SUCCEEDED'),storageVerified=status.supabase_connected===true&&status.supabase_status==='USER_AUTH_AND_DB_READ_VERIFIED';
 if(generation!==state.renderGeneration||state.page!=='settings')return;
 state.settingsProfiles=profiles;state.settingsProjectId=target?.id||null;
 setMain(pageHead('설정','프로젝트별 AI 구성과 비밀값 없는 사내 연결 프로필을 관리합니다.','<button class="btn" data-action="navigate" data-page="settings">설정 새로고침</button>')+`
 <div class="grid-2"><section class="card"><div class="row between"><h2>기본 OpenAI 연결</h2><span class="tag ${connected?'green':'amber'}">${connected?'실제 호출 성공':'미연결'}</span></div><p class="muted">${esc(status.message||status.authentication||'연결 미확인')}</p><p class="small muted">환경: ${esc(status.environment||config.environment)} · 모델: ${esc(status.model||config.provider?.model||'미설정')}</p><p class="small muted">로컬은 Codex OAuth, 배포는 OpenAI API key를 사용합니다. 이 시험은 사내 프로필의 연결 시험이 아닙니다.</p><button class="btn primary" data-action="provider-test">실제 연결 시험</button></section>
 <section class="card"><h2>프로젝트 AI 구성</h2>${target?`<label for="settings-project">설정 대상 프로젝트</label><select id="settings-project">${projects.map(p=>`<option value="${attr(p.id)}" ${p.id===target.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><p class="small muted">현재 작업 프로젝트: ${esc(state.project?.name||'선택 전')}. 아래 저장은 설정 대상 프로젝트에만 적용됩니다.</p><form id="project-provider-form" data-project-id="${attr(target.id)}" data-version="${attr(selection.project_version)}"><label for="project-provider-profile">사용할 AI 구성</label><select id="project-provider-profile"><option value="">기본 OpenAI · 환경별 인증</option>${profiles.filter(p=>['corporate_llm','provider'].includes(p.type)).map(p=>`<option value="${attr(p.id)}" ${selection.selected_profile?.id===p.id?'selected':''}>${esc(p.name)} · 미연결</option>`).join('')}</select><p class="notice ${selection.selected_profile?'review':''}">${selection.selected_profile?'선택된 사내 구성은 NOT_CONFIGURED입니다. AI 호출은 차단되며 기본 OpenAI로 자동 전환하지 않습니다.':'기본 OpenAI를 사용하도록 선택되어 있습니다. 실제 호출 성공 여부는 기본 연결 상태를 확인하세요.'}</p><button class="btn primary" type="submit">프로젝트 AI 구성 저장</button></form>`:'<p>프로젝트를 먼저 생성하세요.</p>'}</section>
 <section class="card"><h2>자료 저장</h2><p>Supabase DB / Storage</p><span class="tag ${storageVerified?'green':'amber'}">${storageVerified?'로그인·DB 조회 확인':'연결 미확인'}</span><p class="small muted">비밀키는 서버 설정으로만 관리합니다.</p></section><section class="card"><h2>기본 로그인</h2><p>Supabase Auth 세션 · 로그인됨</p><p class="small muted">${esc(state.user?.email||'')}</p></section>
 <section class="card"><h2>저장된 사내 연결 프로필</h2>${profiles.length?profiles.map(p=>`<div class="source-ref"><strong>${esc(p.name)}</strong><span class="small muted">${esc(p.type)} · ${esc(p.protocol)} · NOT_CONFIGURED · Rev ${esc(p.version)}</span><button class="btn" data-action="edit-profile" data-id="${attr(p.id)}">프로필 수정</button></div>`).join(''):'<p>저장된 프로필이 없습니다.</p>'}<p class="small muted">저장·선택은 연결 성공을 뜻하지 않습니다. 자격증명을 입력하지 마세요. SSO는 AI 구성으로 선택할 수 없습니다.</p></section>
 <form class="card settings-profile-form"><h2>사내 LLM 구성</h2>${profileFields()}<button class="btn" type="submit">비밀값 없이 저장</button></form><form class="card settings-profile-form"><h2>사내 SSO 구성</h2>${profileFields({type:'sso'})}<button class="btn" type="submit">비밀값 없이 저장</button></form></div>`,generation);
}

function openModal(title,body,footer='',wide=false){state.modalOrigin=document.activeElement;modalRoot.innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${esc(title)}</h2><button class="icon-button" data-action="close-modal" aria-label="닫기">×</button></header><div class="modal-body">${body}</div>${footer?`<footer class="modal-foot">${footer}</footer>`:''}</section></div>`;document.querySelector('.app-layout')?.setAttribute('inert','');modalRoot.querySelector('button,input,select,textarea')?.focus()}
async function openSourcePanel(id,generation=state.renderGeneration){const doc=await api(`/api/documents/${encodeURIComponent(id)}/knowledge`);if(generation!==state.renderGeneration)return;const blocks=asList(doc.blocks).slice(0,40);openModal('원문 근거',`<div class="row"><span class="tag">${esc(doc.approval_status||'승인 상태 미제공')}</span><span class="tag ${doc.extraction_status==='REVIEW_REQUIRED'?'amber':''}">${esc(doc.extraction_status||'추출 상태 미제공')}</span></div><h3 style="margin-top:16px">${esc(doc.filename||'문서')}</h3><p class="small muted">개정 ${esc(doc.revision||'미확정')} · SHA-256 ${esc(doc.sha256||'미제공')}</p>${blocks.length?`<div class="stack">${blocks.map(block=>`<article class="source-ref"><strong>${esc(block.locator||'위치 미제공')}</strong><span>${esc(block.text||'')}</span></article>`).join('')}</div>`:'<p class="notice review">표시할 추출 블록이 없습니다. 원문 파일에서 확인하세요.</p>'}`,'<button class="btn" data-action="close-modal">닫기</button><button class="btn primary" data-action="source-original" data-id="'+attr(id)+'">원문 열기</button>',true)}
function closeModal(){modalRoot.innerHTML='';document.querySelector('.app-layout')?.removeAttribute('inert');state.modalOrigin?.focus?.()}
const filePickerMarkup=()=>`<div class="dropzone" id="dropzone"><p><strong>파일을 끌어 놓거나 선택하세요.</strong></p><p class="small muted">PDF · DOCX · XLSX · PPTX · MD · TXT · CSV · EML</p>${state.config?.provider?.environment==='deployed'?'<p class="small muted">업로드 묶음 최대 3.8 MB · 초과하면 나누어 추가해 주세요.</p>':''}<input id="modal-files" type="file" multiple accept=".pdf,.docx,.xlsx,.pptx,.md,.txt,.csv,.eml"><div id="picked-files" class="file-list"></div><div id="file-error" class="field-error" role="alert"></div></div>`;
function validateUploadFiles(files){const limit=state.config?.upload_limit_bytes||20*1024*1024;if(files.some(file=>file.size>limit))throw new ApiError(413,{code:'FILE_TOO_LARGE',message:`파일당 최대 ${(limit/1000000).toFixed(1)} MB까지 업로드할 수 있습니다.`});if(state.config?.provider?.environment==='deployed'&&files.reduce((sum,file)=>sum+file.size,0)>3800000)throw new ApiError(413,{code:'UPLOAD_BATCH_TOO_LARGE',message:'업로드 묶음은 최대 3.8 MB입니다. 파일을 나누어 추가해 주세요.'});return files}
const selectedFiles=()=>validateUploadFiles([...(document.querySelector('#modal-files')?.files||[])].filter(f=>allowed.test(f.name)));
function showPicked(files){const t=document.querySelector('#picked-files');if(t)t.innerHTML=files.map(f=>`<div class="file-item"><span>${esc(f.name)}</span><span class="small muted">${Math.ceil(f.size/1024)} KB</span></div>`).join('')}
function uploadMessage(payload,successText){const docs=asList(payload,'documents');if(!docs.length)return successText;const rejected=docs.filter(d=>String(d.extraction_status||'').toUpperCase()==='REJECTED'),needsReview=docs.filter(d=>['ERROR','OCR_REQUIRED','UNSUPPORTED','FAILED'].includes(String(d.extraction_status||'').toUpperCase()));if(!rejected.length&&!needsReview.length)return successText;const messages=[];const stored=docs.length-rejected.length;if(stored)messages.push(`원본 ${stored}개 저장`);if(rejected.length)messages.push(`저장 제외 ${rejected.length}개: ${rejected.map(d=>d.filename||d.error_code||'파일명 미제공').join(', ')}`);if(needsReview.length)messages.push(`분석 확인 또는 재처리 필요 ${needsReview.length}개: ${needsReview.map(d=>d.filename||d.id||'문서명 미제공').join(', ')}`);return messages.join('. ')}
document.addEventListener('submit',async e=>{
 if(e.target.id==='login-form'){e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='로그인 중…';try{const p=await api('/api/auth/login',{method:'POST',body:{email:e.target.email.value.trim(),password:e.target.password.value}}),token=p.access_token||p.token||p.session?.access_token,refresh=p.refresh_token||p.session?.refresh_token;if(!token)throw new Error('로그인 응답에 access token이 없습니다.');state.token=token;state.refreshToken=refresh||null;sessionStorage.setItem(tokenKey,token);if(refresh)sessionStorage.setItem(refreshKey,refresh);await initialize()}catch(error){document.querySelector('#login-error').textContent=detailMessage(error);b.disabled=false;b.textContent='로그인'}return}
 if(e.target.id==='query-form'){e.preventDefault();await runKnowledgeQuery(e.target.query.value,document.querySelector('#query-results'))}
 if(e.target.matches('.settings-profile-form')){e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='저장 중…';try{const data=Object.fromEntries(new FormData(e.target)),id=e.target.dataset.profileId;if(id)data.version=Number(e.target.dataset.version);await api('/api/settings/profiles'+(id?'/'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',body:data});if(id)closeModal();invalidateKnowledgeResults();toast('프로필을 저장했습니다. 실제 연결 상태는 미설정입니다.');await navigate('settings')}catch(error){b.disabled=false;b.textContent='비밀값 없이 저장';toast(detailMessage(error))}}
 if(e.target.id==='project-provider-form'){e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('/api/projects/'+encodeURIComponent(e.target.dataset.projectId)+'/provider-profile',{method:'PUT',body:{profile_id:document.querySelector('#project-provider-profile').value||null,version:Number(e.target.dataset.version)}});invalidateKnowledgeResults();toast('프로젝트 AI 구성을 저장했습니다. 실제 연결 여부는 별도로 확인하세요.');await navigate('settings')}catch(error){b.disabled=false;toast(detailMessage(error))}}
 if(e.target.matches('.template-version-form')){e.preventDefault();const b=e.submitter,file=e.target.querySelector('input[type=file]')?.files?.[0];if(!file){toast('등록할 양식 파일을 선택하세요.');return}b.disabled=true;b.textContent='검증 중…';try{const form=new FormData();form.append('file',file);const saved=await api(`/api/templates/${encodeURIComponent(e.target.dataset.templateId)}/versions`,{method:'POST',body:form});toast(`양식 버전을 등록했습니다: ${saved.sha256||saved.version||'해시 미제공'}`);await navigate('templates')}catch(error){b.disabled=false;b.textContent='검증 후 버전 등록';toast(detailMessage(error))}}
});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,originalButtonLabel=b.textContent;try{
 if(a==='navigate')return navigate(b.dataset.page);
 if(a==='logout'){try{await api('/api/auth/logout',{method:'POST'})}finally{sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(refreshKey);sessionStorage.removeItem(projectKey);state.token=null;state.refreshToken=null;renderLogin()}return}
 if(a==='open-project'){setKnowledgeProject(state.projects.find(p=>String(p.id)===b.dataset.id));sessionStorage.setItem(projectKey,b.dataset.id);state.currentDraft=null;state.draftDirty=false;return navigate('project')}
 if(a==='switch-project'){setKnowledgeProject(null);state.currentDraft=null;state.draftDirty=false;sessionStorage.removeItem(projectKey);return navigate('project')}
 if(a==='new-project'){openModal('새 프로젝트 만들기',`<form id="project-form"><label for="project-name">프로젝트 이름</label><input id="project-name" name="name" maxlength="120" required><label for="modal-files">프로젝트 자료 <span class="small muted">선택 · 나중에 추가 가능</span></label>${filePickerMarkup()}<label for="project-kind">프로젝트 용도</label><select id="project-kind" name="kind"><option value="current">검토 프로젝트 · 신규 조건 분석</option><option value="historical">과거 프로젝트 · 경험 근거 축적</option></select><p class="helper small">과거 프로젝트 자료는 신규 조건의 비교 근거로 사용됩니다.</p></form>`,'<button class="btn" data-action="close-modal">취소</button><button class="btn primary" data-action="create-project">프로젝트 생성</button>');return}
 if(a==='create-project'){const name=document.querySelector('#project-name').value.trim(),kind=document.querySelector('#project-kind').value;if(!name){document.querySelector('#project-name').focus();return}const files=selectedFiles();b.disabled=true;b.textContent='생성 중…';const made=await api('/api/projects',{method:'POST',body:{name,kind}}),project=made.project||made;let message=`${kind==='historical'?'과거':'검토'} 프로젝트를 생성했습니다.`;if(files.length){const form=new FormData();files.forEach(f=>form.append('files',f));message=uploadMessage(await mutateSources(`/api/projects/${encodeURIComponent(project.id)}/upload`,{method:'POST',body:form}),'프로젝트와 원본 자료를 등록했습니다.')}state.projects.unshift(project);setKnowledgeProject(project);sessionStorage.setItem(projectKey,project.id);closeModal();toast(message);return navigate('project')}
 if(a==='manage-project'){const p=await api(`/api/projects/${encodeURIComponent(b.dataset.id)}`);state.managedProject=p;openModal('프로젝트 관리',`<label for="managed-project-name">프로젝트 이름</label><input id="managed-project-name" maxlength="150" value="${attr(p.name)}"><p class="helper small">이름을 바꾸면 관련 결과물을 다시 검토·승인해야 합니다.</p><div class="management-danger"><h3>프로젝트 삭제</h3><p class="small muted">업무 목록·검색·분석에서 제외합니다. 등록된 원본과 기록은 보존하며 이 화면에서 영구 삭제하지 않습니다.</p><button class="btn danger" data-action="remove-project">삭제 확인</button></div>`,'<button class="btn" data-action="close-modal">취소</button><button class="btn primary" data-action="rename-project">이름 저장</button>');return}
 if(a==='rename-project'){const p=state.managedProject,name=document.querySelector('#managed-project-name').value.trim();if(!name){document.querySelector('#managed-project-name').focus();return}b.disabled=true;const saved=await api(`/api/projects/${encodeURIComponent(p.id)}`,{method:'PATCH',body:{name,version:p.version}});state.projects=state.projects.map(x=>x.id===saved.id?saved:x);if(state.project?.id===saved.id)setKnowledgeProject(saved);invalidateKnowledgeResults();state.currentDraft=null;state.draftDirty=false;closeModal();toast('프로젝트 이름을 저장했습니다. 관련 결과물을 다시 검토하세요.');return navigate('project')}
 if(a==='remove-project'){const p=state.managedProject;openModal('프로젝트 삭제 확인',`<p><strong>${esc(p.name)}</strong> 프로젝트를 업무 목록에서 제외합니다.</p><p class="notice review">원본과 작업 기록은 보존됩니다. 이 프로젝트의 문서는 검색·비교에서 제외되고 관련 결과물 승인이 해제됩니다.</p><label class="check-line"><input id="project-removal-confirm" type="checkbox">위 내용을 확인했으며 프로젝트를 삭제합니다.</label>`,'<button class="btn" data-action="close-modal">취소</button><button class="btn danger" data-action="confirm-remove-project">프로젝트 삭제</button>');return}
 if(a==='confirm-remove-project'){if(!document.querySelector('#project-removal-confirm').checked){document.querySelector('#project-removal-confirm').focus();return}const p=state.managedProject;b.disabled=true;await api(`/api/projects/${encodeURIComponent(p.id)}`,{method:'DELETE',body:{confirmed:true,version:p.version}});if(state.project?.id===p.id){setKnowledgeProject(null);sessionStorage.removeItem(projectKey)}invalidateKnowledgeResults();state.currentDraft=null;state.draftDirty=false;closeModal();await loadProjects();toast('프로젝트를 업무 목록에서 제외했습니다. 원본과 기록은 보존됩니다.');return navigate('project')}
 if(a==='upload'){openModal('프로젝트 자료 추가',`<p><strong>${esc(state.project.name)}</strong></p>${filePickerMarkup()}`,'<button class="btn" data-action="close-modal">취소</button><button class="btn primary" data-action="confirm-upload">업로드</button>');return}
 if(a==='confirm-upload'){const files=selectedFiles();if(!files.length){document.querySelector('#file-error').textContent='지원되는 파일을 하나 이상 선택하세요.';return}b.disabled=true;b.textContent='업로드 중…';const form=new FormData();files.forEach(f=>form.append('files',f));const message=uploadMessage(await mutateSources(`/api/projects/${encodeURIComponent(state.project.id)}/upload`,{method:'POST',body:form}),'원본을 저장했습니다. 기존 승인 상태는 서버에서 다시 검증됩니다.');state.currentDraft=null;state.draftDirty=false;closeModal();toast(message);return navigate('project')}
 if(a==='original'||a==='source-original'){if(!b.dataset.id)throw new ApiError(422,{detail:{code:'SOURCE_DOCUMENT_MISSING',message:'SourceRef에 원문 문서 ID가 없습니다.'}});await openAuthorized(`/api/documents/${encodeURIComponent(b.dataset.id)}/original`);return}
 if(a==='retry-document'){b.disabled=true;b.textContent='재처리 중…';const result=await mutateSources(`/api/documents/${encodeURIComponent(b.dataset.id)}/retry`,{method:'POST'});toast(`재처리 결과: ${result.extraction_status||'상태 미제공'}`);return navigate('project')}
 if(a==='new-draft'){const templates=asList(await api('/api/templates'),'templates'),rel=templates.filter(t=>String(t.id)===String(b.dataset.kind));if(!rel.length)throw new ApiError(422,{detail:{code:'TEMPLATE_TYPE_MISSING',message:`${draftTitle(b.dataset.kind)} 양식을 찾을 수 없습니다.`}});const template=rel[0],versions=asList(template,'versions'),defaultVersion=template.sha256||versions.find(v=>v.origin==='provided')?.version;openModal(`${draftTitle(b.dataset.kind)} 초안 만들기`,`<p>실제 등록 자료와 출력 종류에 맞는 양식 버전으로 초안을 생성합니다.</p><input id="draft-template" type="hidden" value="${attr(template.id)}"><label for="draft-template-version">양식 버전</label><select id="draft-template-version">${versions.map(v=>{const hash=v.version||v.sha256;return`<option value="${attr(hash)}" ${String(hash)===String(defaultVersion)?'selected':''}>${esc(v.filename||template.filename||template.name)} · ${esc(v.origin||'출처 미제공')} · ${esc(hash)}</option>`}).join('')}</select><p class="helper small">제공 원본 버전이 기본입니다. 등록된 다른 버전은 명시적으로 선택해야 적용됩니다.</p><label for="draft-mode">분석 방식</label><select id="draft-mode"><option value="rules">규칙 기반 비교</option><option value="ai">AI Insight</option></select><p class="helper small">AI 연결이 확인되지 않으면 서버가 503과 미연결 상태를 반환합니다.</p>`,'<button class="btn" data-action="close-modal">취소</button><button class="btn primary" data-action="create-draft" data-kind="'+attr(b.dataset.kind)+'">초안 생성</button>');return}
 if(a==='create-draft'){const projectId=state.project.id,generation=state.renderGeneration;b.disabled=true;b.textContent='생성 중…';const p=await api(`/api/projects/${encodeURIComponent(state.project.id)}/drafts`,{method:'POST',body:{kind:b.dataset.kind,mode:document.querySelector('#draft-mode').value,template_id:document.querySelector('#draft-template').value,template_version:document.querySelector('#draft-template-version').value}});if(applyDraftResponse(p,projectId,generation))closeModal();return}
 if(a==='draft-evidence'){const row=state.currentDraft?.rows?.[Number(b.dataset.rowIndex)];if(!row)return;openModal('항목별 원문 근거',draftEvidenceMarkup(row),'<button class="btn" data-action="close-modal">닫기</button>',true);return}
 if(a==='open-draft'){const projectId=state.project.id,generation=state.renderGeneration;b.disabled=true;const p=await api(`/api/drafts/${encodeURIComponent(b.dataset.id)}`);applyDraftResponse(p,projectId,generation);return}
 if(a==='save-draft'){const projectId=state.project.id,generation=state.renderGeneration;b.disabled=true;b.textContent='저장 중…';const rows=[...document.querySelectorAll('#draft-form tr[data-row]')].map((tr,i)=>({...state.currentDraft.rows[i],...Object.fromEntries([...tr.querySelectorAll('input,textarea')].map(f=>[f.name,f.value]))})),p=await api(`/api/drafts/${encodeURIComponent(state.currentDraft.id)}`,{method:'PATCH',body:{rows,template_id:state.currentDraft.template_id,template_version:document.querySelector('#draft-bound-version')?.value||state.currentDraft.template_version,revision:state.currentDraft.revision}});applyDraftResponse(p,projectId,generation);toast('수정 내용을 새 개정으로 저장했습니다. 기존 승인은 무효화됩니다.');return}
 if(a==='approve-draft'){openModal('결과물 최종 승인','<p>데이터 등록 승인과 별개의 최종 결과물 승인입니다.</p><label class="check-line"><input id="approval-check" type="checkbox">현재 입력·양식·원문 근거와 REVIEW_REQUIRED 항목을 확인했습니다.</label>','<button class="btn" data-action="close-modal">돌아가기</button><button class="btn primary" data-action="confirm-approval">최종 승인</button>');return}
 if(a==='confirm-approval'){if(!document.querySelector('#approval-check').checked){document.querySelector('#approval-check').focus();return}const projectId=state.project.id,generation=state.renderGeneration;b.disabled=true;b.textContent='승인 중…';const p=await api(`/api/drafts/${encodeURIComponent(state.currentDraft.id)}/approve`,{method:'POST',body:{confirmed:true,revision:state.currentDraft.revision}});if(applyDraftResponse(p,projectId,generation))closeModal();toast('현재 버전의 결과물을 승인했습니다.');return}
 if(a==='export-draft'){const draft=state.currentDraft,region=document.querySelector('#download-status');if(!draft||draft.status!=='approved'||state.draftDirty)throw new ApiError(409,{code:'APPROVAL_REQUIRED',message:'현재 내용을 저장하고 최종 승인한 뒤 파일을 생성하세요.'});b.disabled=true;b.textContent='파일 생성 중…';if(region)region.textContent='승인된 내용과 원본을 검증하고 파일을 생성하고 있습니다. 완료되면 다운로드 링크가 표시됩니다.';try{const result=await downloadAuthorized(`/api/drafts/${encodeURIComponent(draft.id)}/export`,null,'POST');if(region)region.innerHTML=`<p>파일이 준비되었습니다. 자동 다운로드가 시작되지 않으면 <a class="link-button" href="${attr(result.url)}" download="${attr(result.filename)}">여기를 눌러 다운로드</a>하세요.</p>`;toast('파일 생성이 완료됐습니다. 화면의 다운로드 링크로도 저장할 수 있습니다.')}catch(error){if(region)region.innerHTML=`<p class="notice error" role="alert">${esc(detailMessage(error))}</p>`;throw error}finally{b.disabled=false;b.textContent='실제 파일 내보내기'}return}
 if(a==='mode'){const input=document.querySelector('#query');if(input)setKnowledgeQuery(input.value);setKnowledgeMode(b.dataset.mode);return navigate('knowledge')}if(a==='select-comparison'){state.selectedComparisonId=b.dataset.rowId||null;return navigate('library')}if(a==='graph-document'){if(!b.dataset.id)throw new ApiError(422,{detail:{code:'SOURCE_DOCUMENT_MISSING',message:'지식 연결에 원문 문서 ID가 없습니다.'}});return openSourcePanel(b.dataset.id,state.renderGeneration)}
 if(a==='template-original'){const version=b.dataset.version?`?version=${encodeURIComponent(b.dataset.version)}`:'';await downloadAuthorized(`/api/templates/${encodeURIComponent(b.dataset.id)}/original${version}`,b.dataset.name);return}
 if(a==='edit-profile'){const p=state.settingsProfiles.find(p=>p.id===b.dataset.id);if(!p)return;openModal('사내 연결 프로필 수정',`<form class="settings-profile-form" data-profile-id="${attr(p.id)}" data-version="${attr(p.version)}">${profileFields(p)}<p class="small muted">실제 연결은 미설정 상태로 유지됩니다.</p><button class="btn primary" type="submit">수정 저장</button></form>`);return}
 if(a==='provider-test'){b.disabled=true;b.textContent='시험 중…';try{const p=await api('/api/provider/test',{method:'POST'});toast(p.connected&&p.inference==='SUCCEEDED'?'실제 모델 호출 시험이 성공했습니다.':`연결 미확인: ${p.authentication||p.message||'실제 호출 성공 근거가 없습니다.'}`);await navigate('settings')}finally{b.disabled=false;b.textContent='실제 연결 시험'}return}
 if(a==='folder-candidates'){const p=await api('/api/import/candidates'),c=asList(p,'candidates');openModal('기존 폴더 자료 확인',c.length?`<p>승인 전에는 이름과 크기만 확인합니다.</p><label for="import-project">등록할 프로젝트</label><select id="import-project">${state.projects.map(project=>`<option value="${attr(project.id)}" ${String(project.id)===String(state.project?.id)?'selected':''}>${esc(project.name)} · ${project.kind==='historical'?'과거 프로젝트':'검토 프로젝트'}</option>`).join('')}</select><form id="candidate-form" class="stack">${c.map(i=>`<label class="check-line"><input type="checkbox" name="path" value="${attr(i.path)}"><span><strong>${esc(i.name||i.filename||i.path)}</strong><br><span class="small muted">${esc(i.size??'크기 미제공')} bytes</span></span></label>`).join('')}</form><label class="check-line"><input id="candidate-confirm" type="checkbox">선택한 경로만 지식화 대상으로 승인합니다.</label>`:empty('등록 후보가 없습니다','허용된 INPUT 범위에서 확인할 후보가 없습니다.'),c.length?'<button class="btn" data-action="close-modal">취소</button><button class="btn primary" data-action="approve-candidates">선택 승인</button>':'<button class="btn" data-action="close-modal">닫기</button>',true);return}
 if(a==='approve-candidates'){const paths=[...document.querySelectorAll('input[name=path]:checked')].map(i=>i.value),projectId=document.querySelector('#import-project')?.value;if(!projectId||!paths.length||!document.querySelector('#candidate-confirm').checked){toast('프로젝트, 대상, 확인 항목을 모두 선택하세요.');return}b.disabled=true;await mutateSources('/api/import/approve',{method:'POST',body:{project_id:projectId,paths,confirmed:true}});closeModal();toast('선택한 폴더 자료를 등록했습니다.');return navigate('management')}
 if(a==='close-modal')return closeModal()
 }catch(error){b.disabled=false;b.textContent=originalButtonLabel;toast(detailMessage(error))}});
document.addEventListener('change',e=>{if(e.target.id==='settings-project'){state.settingsProjectId=e.target.value;navigate('settings');return}if(e.target.id==='search-scope'){setKnowledgeScope(e.target.value);const region=document.querySelector('#query-results');if(region)region.innerHTML=empty('검색 범위가 변경되었습니다','질문과 선택한 범위를 확인한 뒤 다시 검색하세요.');return}if(e.target.id==='modal-files'){const all=[...e.target.files],valid=all.filter(f=>allowed.test(f.name));showPicked(valid);document.querySelector('#file-error').textContent=valid.length===all.length?'':`지원되지 않는 형식 ${all.length-valid.length}개를 제외했습니다.`}});
document.addEventListener('input',e=>{if(e.target.id==='query'){if(setKnowledgeQuery(e.target.value)){const region=document.querySelector('#query-results');if(region)region.innerHTML=empty('질문을 입력하세요','질문이 변경되었습니다. 검색 또는 적용 검토를 다시 실행하세요.')}return}if(!e.target.closest('#draft-form'))return;state.draftDirty=true;const approve=document.querySelector('[data-action="approve-draft"]'),exportButton=document.querySelector('[data-action="export-draft"]'),status=document.querySelector('#draft-region .tag'),notice=document.querySelector('#draft-region .notice');if(approve)approve.disabled=true;if(exportButton)exportButton.disabled=true;if(status){status.textContent='저장되지 않은 변경';status.classList.remove('green');status.classList.add('amber')}if(notice){notice.textContent='변경 내용을 저장해야 승인 또는 내보내기를 할 수 있습니다.';notice.classList.add('review')}});
document.addEventListener('dragover',e=>{const z=e.target.closest('#dropzone');if(z){e.preventDefault();z.classList.add('dragover')}});
document.addEventListener('dragleave',e=>e.target.closest('#dropzone')?.classList.remove('dragover'));
document.addEventListener('drop',e=>{const z=e.target.closest('#dropzone');if(!z)return;e.preventDefault();z.classList.remove('dragover');const input=document.querySelector('#modal-files');try{input.files=e.dataTransfer.files}catch{const error=document.querySelector('#file-error');if(error)error.textContent='드롭한 파일을 불러올 수 없습니다. 파일 선택 버튼을 사용하세요.';return}input.dispatchEvent(new Event('change',{bubbles:true}))});
document.addEventListener('keydown',e=>{const modal=modalRoot.querySelector('.modal');if(!modal)return;if(e.key==='Escape'){closeModal();return}if(e.key==='Tab'){const f=[...modal.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')],first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
window.addEventListener('hashchange',async()=>{if(!state.token)return;const route=routeFromHash();if(route.source){state.pendingSource=route.source;await openSourcePanel(route.source,state.renderGeneration);return}state.pendingSource=null;if(route.page!==state.page)navigate(route.page)});
initialize();
