'use strict';
// Actual frontend and API with explicit TEST_STORAGE_INJECTED, not live Supabase proof.
const {chromium,request}=require('../../tools/web/node_modules/playwright');
const {expect}=require('../../tools/web/node_modules/playwright/test');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http');
const {base,verifyFixture}=require('./fixture_target.cjs');
const ROOT=path.resolve(__dirname,'../..'),out=path.join(ROOT,'ops/runtime/demo/ui-v6-management');fs.mkdirSync(out,{recursive:true});
(async()=>{const api=await request.newContext({baseURL:base,extraHTTPHeaders:{Authorization:'Bearer browser-alice'}});const report={boundary:'TEST_STORAGE_INJECTED',product:'RE:Build Agent',checks:[],screenshots:[],status:'RUNNING'};await verifyFixture(api,report);const browser=await chromium.launch({headless:false});let reference;
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByLabel('이메일',{exact:true}).fill('browser-alice@example.invalid');await page.getByLabel('비밀번호',{exact:true}).fill('synthetic-test-only');await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page.locator('.intro')).toBeVisible();
const metrics=await page.evaluate(()=>({sidebar:getComputedStyle(document.querySelector('.sidebar')).backgroundColor,width:document.querySelector('.sidebar').getBoundingClientRect().width,title:getComputedStyle(document.querySelector('h1')).fontSize}));assert.equal(metrics.sidebar,'rgb(255, 255, 255)');assert.equal(metrics.width,220);assert.equal(metrics.title,'30px');
await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();await page.getByLabel('프로젝트 이름',{exact:true}).fill('UI 검증 · 과거 프로젝트');await page.getByLabel('프로젝트 용도',{exact:true}).selectOption('historical');await page.locator('#modal-files').setInputFiles({name:'history.txt',mimeType:'text/plain',buffer:Buffer.from('Notice period: 28 calendar days.\nLessons learned: late notice creates risk.')});await page.getByRole('button',{name:'프로젝트 생성',exact:true}).click();await expect(page.getByRole('heading',{name:'UI 검증 · 과거 프로젝트',exact:true})).toBeVisible();await page.getByRole('button',{name:'프로젝트 변경',exact:true}).click();
await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();await page.getByLabel('프로젝트 이름',{exact:true}).fill('UI 검증 · 신규 프로젝트');await page.locator('#modal-files').setInputFiles({name:'current.txt',mimeType:'text/plain',buffer:Buffer.from('Notice period: 14 calendar days.\nEmployer: synthetic browser fixture.')});assert(await page.locator('#project-name').evaluate(e=>Boolean(e.compareDocumentPosition(document.querySelector('#modal-files'))&Node.DOCUMENT_POSITION_FOLLOWING)));await page.getByRole('button',{name:'프로젝트 생성',exact:true}).click();await expect(page.getByRole('heading',{name:'UI 검증 · 신규 프로젝트',exact:true})).toBeVisible();await page.screenshot({path:path.join(out,'project-desktop.png'),fullPage:true});report.screenshots.push('project-desktop.png');
await page.getByRole('button',{name:'프로젝트 관리',exact:true}).click();await page.getByLabel('프로젝트 이름',{exact:true}).fill('UI 검증 · 이름 수정 완료');await page.getByRole('button',{name:'이름 저장',exact:true}).click();await expect(page.getByRole('heading',{name:'UI 검증 · 이름 수정 완료',exact:true})).toBeVisible();report.checks.push('Rename through versioned project API');
await page.getByRole('button',{name:'지식 자료실',exact:true}).click();await expect(page.locator('.graph-row').first()).toBeVisible();await expect(page.locator('.comparison-side')).toHaveCount(2);await page.screenshot({path:path.join(out,'knowledge-desktop.png'),fullPage:true});report.screenshots.push('knowledge-desktop.png');const sid=await page.locator('.graph-row [data-action=graph-document]').first().getAttribute('data-id');await page.locator('.graph-row [data-action=graph-document]').first().click();await expect(page.getByRole('dialog')).toContainText('SHA-256');await page.keyboard.press('Escape');report.checks.push('Source-backed graph rows and evidence dialog');
await page.getByRole('button',{name:'프로젝트',exact:true}).click();await page.getByRole('button',{name:'프로젝트 변경',exact:true}).click();await page.screenshot({path:path.join(out,'home-desktop.png'),fullPage:true});report.screenshots.push('home-desktop.png');await page.setViewportSize({width:375,height:812});await page.emulateMedia({reducedMotion:'reduce'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'home-mobile.png'),fullPage:true});report.screenshots.push('home-mobile.png');
await page.getByRole('button',{name:'UI 검증 · 이름 수정 완료 관리',exact:true}).click();await page.getByRole('button',{name:'삭제 확인',exact:true}).click();await page.getByRole('button',{name:'프로젝트 삭제',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('#project-removal-confirm').check();await page.getByRole('button',{name:'프로젝트 삭제',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'UI 검증 · 이름 수정 완료',exact:true})).toHaveCount(0);report.checks.push('Confirmation required before source-preserving project deletion');assert.equal(errors.length,0);
// Read-only serving of original reference files for a side-by-side visual record.
reference=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1').pathname,root=path.join(ROOT,'docs/ui-review'),file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end()}const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file))});await new Promise(r=>reference.listen(0,'127.0.0.1',r));await page.setViewportSize({width:1440,height:1000});await page.goto(`http://127.0.0.1:${reference.address().port}/index.html`);await expect(page.locator('.intro')).toBeVisible();await page.screenshot({path:path.join(out,'reference-home-desktop.png'),fullPage:true});report.screenshots.push('reference-home-desktop.png');report.status='PASSED';report.at=new Date().toISOString();report.metrics=metrics;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();await api.dispose();if(reference)await new Promise(r=>reference.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
