const {chromium,request}=require('../../tools/web/node_modules/playwright'); const {expect}=require('../../tools/web/node_modules/playwright/test');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {base,verifyFixture}=require('./fixture_target.cjs');const out=path.resolve('ops/runtime');
const report={boundary:'TEST_STORAGE_INJECTED',started:new Date().toISOString(),checks:[],errors:[]};
const check=(name,detail)=>report.checks.push({name,status:'PASS',detail});
(async()=>{
 const api=await request.newContext({baseURL:base,extraHTTPHeaders:{Authorization:'Bearer browser-alice'}});
 await verifyFixture(api,report);
 expect(await(await api.get('/api/projects')).json()).toEqual([]);
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));
 try {
 await page.goto(base);await page.getByLabel('이메일',{exact:true}).fill('browser-alice@example.invalid');await page.getByLabel('비밀번호',{exact:true}).fill('wrong');await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page.locator('#login-error')).toContainText('LOGIN_FAILED');check('Synthetic invalid login error');
 await page.getByLabel('비밀번호',{exact:true}).fill('synthetic-test-only');await page.getByRole('button',{name:'로그인',exact:true}).click();await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();
 await page.getByLabel('프로젝트 이름',{exact:true}).fill('Browser historical fixture');await page.getByLabel('프로젝트 용도',{exact:true}).selectOption('historical');await page.locator('#modal-files').setInputFiles({name:'browser-history.txt',mimeType:'text/plain',buffer:Buffer.from('Notice period: 28 calendar days.\nLessons learned: late notice causes risk.')});await page.getByRole('button',{name:'프로젝트 생성',exact:true}).click();await expect(page.getByRole('heading',{name:'Browser historical fixture',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'browser-history.txt',exact:true})).toBeVisible();check('Zero-state historical project and source created through UI');await page.getByRole('button',{name:'프로젝트 변경',exact:true}).click();await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();
 await page.getByLabel('프로젝트 이름',{exact:true}).fill('Browser unseen project');await page.locator('#modal-files').setInputFiles('ops/runtime/browser-new.docx');
 const bytes=fs.readFileSync('ops/runtime/browser-new.docx'),hash=crypto.createHash('sha256').update(bytes).digest('hex');
 const before=await api.get('/api/management');expect(JSON.stringify(await before.json())).not.toContain(hash);check('New DOCX hash absent before upload',hash);
 await page.getByRole('button',{name:'프로젝트 생성',exact:true}).click();await expect(page.getByRole('heading',{name:'Browser unseen project',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'browser-new.docx',exact:true})).toBeVisible();
 const projects=await (await api.get('/api/projects')).json(),pid=projects.find(p=>p.name==='Browser unseen project').id;
 const docs=await(await api.get(`/api/projects/${pid}/documents`)).json(),doc=docs[0];expect(doc.sha256).toBe(hash);expect(JSON.stringify(doc.blocks)).toContain('17 calendar days');check('Real DOCX upload parser and hash');
 await page.locator('[data-action="new-draft"][data-kind="itb"]').click();await page.getByRole('button',{name:'초안 생성',exact:true}).click();await expect(page.locator('#draft-form')).toBeVisible();await expect(page.getByRole('button',{name:'실제 파일 내보내기',exact:true})).toBeDisabled();await expect(page.locator('#draft-form textarea[name="current"]').first()).toContainText('17 calendar days');await expect(page.locator('#draft-form textarea[name="past"]').first()).toContainText('28 calendar days');check('Actual comparison and unapproved export disabled');
 await page.getByLabel('1번 판단 근거',{exact:true}).fill('Browser reviewer verified the uploaded notice period.');await expect(page.locator('[data-action=approve-draft]')).toBeDisabled();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();check('Unsaved draft edits block approval and export');await page.getByRole('button',{name:'수정 저장',exact:true}).click();await expect(page.getByRole('heading',{name:/ITB 분석표 · Rev 2/})).toBeVisible();
 await page.getByRole('button',{name:'검토 후 승인',exact:true}).click();await page.locator('#approval-check').check();await page.getByRole('button',{name:'최종 승인',exact:true}).click();await expect(page.getByRole('button',{name:'실제 파일 내보내기',exact:true})).toBeEnabled();
 await page.reload();const itbCard=page.locator('.template-card').filter({has:page.getByRole('heading',{name:'ITB 분석표',exact:true})});await itbCard.locator('[data-action=open-draft]').first().click();await expect(page.getByRole('heading',{name:'ITB 분석표 · Rev 2',exact:true})).toBeVisible();await expect(page.locator('[data-action=export-draft]')).toBeEnabled();check('Approved draft persisted and reopened after refresh');await page.getByLabel('1번 판단 근거',{exact:true}).fill('Browser reviewer verified the uploaded notice period. Reopened revision.');await expect(page.locator('[data-action=approve-draft]')).toBeDisabled();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();await page.locator('[data-action=save-draft]').click();await expect(page.getByRole('heading',{name:'ITB 분석표 · Rev 3',exact:true})).toBeVisible();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();await expect(page.locator('[data-action=approve-draft]')).toBeEnabled();check('Approved edit saved as new revision invalidates approval');await page.locator('[data-action=approve-draft]').click();await page.locator('#approval-check').check();await page.getByRole('button',{name:'최종 승인',exact:true}).click();await expect(page.locator('[data-action=export-draft]')).toBeEnabled();check('Edited draft reapproved before actual export');
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'실제 파일 내보내기',exact:true}).click();await(await downloaded).saveAs(path.join(out,'browser-result.xlsx'));check('Draft edit approve actual XLSX download');
 for(const item of [{kind:'risk',field:'1번 대응',value:'Browser risk mitigation reviewed.',file:'browser-risk.xlsx',heading:'Risk Register'},{kind:'slides',field:'1번 슬라이드 결정 사항',value:'Browser committee decision reviewed.',file:'browser-committee.pptx',heading:'심의장표'}]) {
   await page.locator(`[data-action="new-draft"][data-kind="${item.kind}"]`).click();
   await expect(page.locator('#draft-template')).toHaveValue(item.kind);check(item.kind+' default matching template');
   await page.getByRole('button',{name:'초안 생성',exact:true}).click();
   await expect(page.getByRole('heading',{name:item.heading+' · Rev 1',exact:true})).toBeVisible();
   if(item.kind==='slides'){try{await expect(page.locator('#draft-form tr[data-row]')).toHaveCount(5);check('Committee five editable slide rows')}catch(e){report.checks.push({name:'Committee five editable slide rows',status:'FAIL',detail:e.message});}}
   await expect(page.getByRole('button',{name:'실제 파일 내보내기',exact:true})).toBeDisabled();
   await page.getByLabel(item.field,{exact:true}).fill(item.value);if(item.kind==='slides'){await page.getByLabel('1번 슬라이드 제목',{exact:true}).fill('Browser committee reviewed title');const body=page.getByLabel('1번 슬라이드 핵심 내용',{exact:true});await body.fill((await body.inputValue())+' Browser committee reviewed body.');}
   await page.getByRole('button',{name:'수정 저장',exact:true}).click();
   await expect(page.getByRole('heading',{name:item.heading+' · Rev 2',exact:true})).toBeVisible();
   await expect(page.getByLabel(item.field,{exact:true})).toHaveValue(item.value);
   await page.getByRole('button',{name:'검토 후 승인',exact:true}).click();
   await page.locator('#approval-check').check();await page.getByRole('button',{name:'최종 승인',exact:true}).click();
   await expect(page.getByRole('button',{name:'실제 파일 내보내기',exact:true})).toBeEnabled();
   const received=page.waitForEvent('download');await page.getByRole('button',{name:'실제 파일 내보내기',exact:true}).click();await(await received).saveAs(path.join(out,item.file));
   check(item.heading+' actual draft edit approval download',item.file);
 }
 await page.getByRole('button',{name:'지식 자료실',exact:true}).click();await expect(page.locator('.comparison-side')).toHaveCount(2);try { await expect(page.locator('.comparison-side').first()).toContainText('28 calendar days');await expect(page.locator('.comparison-side').last()).toContainText('17 calendar days');check('Both historical and current source panels'); } catch(e) { report.checks.push({name:'Both historical and current source panels',status:'FAIL',detail:e.message}); }
 const knowledge=await(await api.get(`/api/projects/${pid}/knowledge`)).json();for(const node of knowledge.nodes.filter(n=>n.type==='knowledge')){await page.locator(`[data-action=select-comparison][data-row-id="${node.row_id}"]`).click();const row=knowledge.comparisons.find(r=>r.id===node.row_id);await expect(page.locator('.comparison').locator('..')).toContainText(row.title);}await page.locator(`[data-action=graph-document][data-id="${doc.id}"]`).first().click();await expect(page.getByRole('dialog')).toContainText('17 calendar days');await page.getByRole('button',{name:'닫기',exact:true}).last().click();expect(knowledge.edges.some(e=>e.source_ref?.document_id===doc.id)).toBeTruthy();check('Graph knowledge IDs map to actual comparison and source edges');
 await page.goto(base+'/#source='+doc.id);await expect(page.getByRole('dialog')).toContainText('17 calendar days');await expect(page.getByRole('dialog')).toContainText(hash);await page.getByRole('button',{name:'닫기',exact:true}).last().click();check('Direct source hash route evidence');
 await page.getByRole('button',{name:'데이터 관리',exact:true}).click();await expect(page.getByRole('heading',{name:'데이터 관리',exact:true})).toBeVisible();await expect(page.locator('.stats')).toContainText('과거 보유 문서');check('Management actual data');
 await page.getByRole('button',{name:'표준 양식',exact:true}).click();await expect(page.locator('[data-action="template-original"]')).toHaveCount(7);check('Seven actual templates');
 const templateBytes=fs.readFileSync('ops/runtime/browser-template.xlsx'),templateHash=crypto.createHash('sha256').update(templateBytes).digest('hex');const templateForm=page.locator('.template-version-form[data-template-id="itb"]');await templateForm.locator('input[type=file]').setInputFiles('ops/runtime/browser-template.xlsx');await templateForm.getByRole('button',{name:'검증 후 버전 등록',exact:true}).click();await expect(page.locator(`[data-action=template-original][data-version="${templateHash}"]`)).toBeVisible();const versionDownload=page.waitForEvent('download');await page.locator(`[data-action=template-original][data-version="${templateHash}"]`).click();const versionPath=path.join(out,'browser-template-downloaded.xlsx');await(await versionDownload).saveAs(versionPath);expect(crypto.createHash('sha256').update(fs.readFileSync(versionPath)).digest('hex')).toBe(templateHash);check('Uploaded template version listed and downloaded byte-identical');
 await page.getByRole('button',{name:'프로젝트',exact:true}).click();await page.locator('[data-action=new-draft][data-kind=itb]').click();await page.getByLabel('양식 버전',{exact:true}).selectOption(templateHash);await page.getByRole('button',{name:'초안 생성',exact:true}).click();await expect(page.getByLabel('결과물 양식 버전')).toHaveValue(templateHash);await page.locator('[data-action=approve-draft]').click();await page.locator('#approval-check').check();await page.getByRole('button',{name:'최종 승인',exact:true}).click();const customDownload=page.waitForEvent('download');await page.locator('[data-action=export-draft]').click();await(await customDownload).saveAs(path.join(out,'browser-custom-template-result.xlsx'));await page.reload();const customCard=page.locator('.template-card').filter({has:page.getByRole('heading',{name:'ITB 분석표',exact:true})});const savedDrafts=await(await api.get(`/api/projects/${pid}/drafts`)).json();const customDraft=savedDrafts.find(d=>d.template_version===templateHash);expect(customDraft).toBeTruthy();await customCard.locator(`[data-action=open-draft][data-id="${customDraft.id}"]`).click();await expect(page.getByLabel('결과물 양식 버전')).toHaveValue(templateHash);await expect(page.locator('[data-action=export-draft]')).toBeEnabled();check('Uploaded template version selected approved exported and reopened');
 await page.getByRole('button',{name:'설정',exact:true}).click();await expect(page.getByRole('heading',{name:'사내 SSO 구성',exact:true})).toBeVisible();await page.getByRole('button',{name:'실제 연결 시험',exact:true}).click();await expect(page.locator('#toast')).toContainText('CODEX_LOGIN_REQUIRED');expect(await page.locator('#toast').innerText()).not.toContain('성공');await expect(page.getByRole('button',{name:'실제 연결 시험',exact:true})).toBeEnabled();check('Provider failure does not claim success');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'browser-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(overflow.scroll).toBeLessThanOrEqual(overflow.width+1);check('Mobile no horizontal document overflow',overflow);
 await page.route('**/api/templates',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:{code:'SYNTHETIC_OUTAGE',message:'Synthetic outage'}})}));await page.getByRole('button',{name:'표준 양식',exact:true}).click();await expect(page.getByRole('alert')).toContainText('SYNTHETIC_OUTAGE');await page.unroute('**/api/templates');await page.getByRole('button',{name:'다시 시도',exact:false}).click();await expect(page.locator('[data-action="template-original"]')).toHaveCount(8);check('Service error retry recovery');
 await page.getByRole('button',{name:'로그아웃',exact:true}).click();await expect(page.getByRole('heading',{name:'워크스페이스 로그인',exact:true})).toBeVisible();check('Logout');
 expect(report.errors).toEqual([]);expect(report.checks.filter(c=>c.status==='FAIL')).toEqual([]);
 }catch(e){report.failure=e.stack;await page.screenshot({path:path.join(out,'browser-failure.png'),fullPage:true});process.exitCode=1;}finally{report.finished=new Date().toISOString();fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'browser-report-'+report.started.replace(/[:.]/g,'-')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await api.dispose();}
})().catch(e=>{console.error(e);process.exitCode=1});
