'use strict';
const {chromium,request}=require('../../tools/web/node_modules/playwright');
const {expect}=require('../../tools/web/node_modules/playwright/test');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {base,verifyFixture}=require('./fixture_target.cjs');const out=path.resolve('ops/runtime');
const report={boundary:'TEST_STORAGE_INJECTED',scenario:'Slide detail disclosure and rejected edit preservation',started:new Date().toISOString(),checks:[],errors:[]};
const record=(name,detail)=>report.checks.push({name,status:'PASS',detail});
(async()=>{
 const api=await request.newContext({baseURL:base,extraHTTPHeaders:{Authorization:'Bearer browser-alice'}});
 await verifyFixture(api,report);
 expect(await(await api.get('/api/projects')).json()).toEqual([]);
 const browser=await chromium.launch({headless:true}),page=await browser.newPage();let exportRequests=0;
 page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/export'))exportRequests++});
 try{
  const marker=crypto.randomUUID();await page.goto(base);await page.getByLabel('이메일',{exact:true}).fill('browser-alice@example.invalid');await page.getByLabel('비밀번호',{exact:true}).fill('synthetic-test-only');await page.getByRole('button',{name:'로그인',exact:true}).click();
  await page.getByRole('button',{name:'새 프로젝트',exact:true}).click();await page.getByLabel('프로젝트 이름',{exact:true}).fill('Slide limits '+marker);await page.locator('#modal-files').setInputFiles({name:'slide-original-'+marker+'.txt',mimeType:'text/plain',buffer:Buffer.from('Employer: Browser Slide Company.\nNotice period: 37 calendar days.\nSynthetic marker: '+marker)});await page.getByRole('button',{name:'프로젝트 생성',exact:true}).click();
  await page.locator('[data-action=new-draft][data-kind=slides]').click();const createdPromise=page.waitForResponse(r=>r.url().endsWith('/drafts')&&r.request().method()==='POST');await page.getByRole('button',{name:'초안 생성',exact:true}).click();const createdResponse=await createdPromise;expect(createdResponse.status()).toBe(201);const draft=await createdResponse.json();
  await expect(page.locator('#draft-form tr[data-row]')).toHaveCount(5);await expect(page.locator('#draft-region')).toContainText('원문 발췌');await expect(page.locator('#draft-region')).toContainText('표시 한도');await expect(page.locator('#draft-region')).toContainText('PPTX 발표자 노트');record('Five editable rows disclose bounded original excerpts and full notes');
  const detail=page.locator('#draft-form details').filter({hasText:'37 calendar days'}).first();await detail.locator('summary').click();await expect(detail.locator('pre')).toBeVisible();await expect(detail.locator('pre')).toContainText('37 calendar days');record('Expanded detail exposes actual original value before approval');
  async function approve(){await page.locator('[data-action=approve-draft]').click();await page.locator('#approval-check').check();await page.getByRole('button',{name:'최종 승인',exact:true}).click();await expect(page.locator('[data-action=export-draft]')).toBeEnabled();}
  await approve();const before=await(await api.get('/api/drafts/'+draft.id)).json();expect(before.status).toBe('approved');record('Bounded valid slide draft approved');
  const longText='매우 긴 한글 검토 내용으로 발표 장표의 표시 한도를 검증합니다. '.repeat(400),current=page.getByLabel('1번 슬라이드 핵심 내용',{exact:true});await current.fill(longText);await expect(page.locator('[data-action=approve-draft]')).toBeDisabled();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();
  const rejectedPromise=page.waitForResponse(r=>r.url().endsWith('/api/drafts/'+draft.id)&&r.request().method()==='PATCH');await page.locator('[data-action=save-draft]').click();const rejected=await rejectedPromise;expect(rejected.status()).toBe(422);expect((await rejected.json()).detail.code).toBe('SLIDE_CONTENT_TOO_LONG');await expect(page.locator('#toast')).toContainText('분량');await expect(page.locator('#toast')).toContainText('SLIDE_CONTENT_TOO_LONG');record('Oversized Korean content rejected with 422 and friendly length message');
  const after=await(await api.get('/api/drafts/'+draft.id)).json();expect(after.status).toBe('approved');expect(after.revision).toBe(before.revision);expect(after.rows).toEqual(before.rows);record('Rejected edit leaves server approved revision and all row contents unchanged');
  await expect(current).toHaveValue(longText);await expect(page.locator('[data-action=approve-draft]')).toBeDisabled();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();record('UI retains oversized unsaved input and blocks approval/export');
  const shortened='Employer: Browser Slide Company. 검토 완료.';await current.fill(shortened);await page.locator('[data-action=save-draft]').click();await expect(page.getByRole('heading',{name:'심의장표 · Rev '+(before.revision+1),exact:true})).toBeVisible();await expect(page.locator('[data-action=export-draft]')).toBeDisabled();await expect(page.locator('[data-action=approve-draft]')).toBeEnabled();const revised=await(await api.get('/api/drafts/'+draft.id)).json();expect(revised.status).toBe('draft');expect(revised.rows[0].current).toBe(shortened);record('Shortened edit saves a new revision and invalidates prior approval');
  await approve();const finalDraft=await(await api.get('/api/drafts/'+draft.id)).json();expect(finalDraft.status).toBe('approved');expect(finalDraft.revision).toBe(before.revision+1);record('Shortened revision reapproved successfully');expect(exportRequests).toBe(0);expect(report.errors).toEqual([]);record('No exports requested and no browser JavaScript errors');
 }catch(e){report.failure=e.stack;process.exitCode=1;await page.screenshot({path:path.join(out,'browser-slide-limits-failure-'+report.started.replace(/[:.]/g,'-')+'.png'),fullPage:true});}
 finally{report.finished=new Date().toISOString();const filename='browser-slide-limits-'+report.started.replace(/[:.]/g,'-')+'.json';fs.writeFileSync(path.join(out,filename),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,evidence:filename},null,2));await browser.close();await api.dispose();}
})().catch(e=>{console.error(e);process.exitCode=1});
