'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {requireProductResponse}=require('../../ops/demo_browser.cjs');
function response(status,body){return {status:()=>status,json:async()=>body};}
test('approval503 records only allowlisted code and fails immediately',async()=>{const diagnostics=[];await assert.rejects(requireProductResponse(response(503,{detail:{code:'SERVICE_UNAVAILABLE',message:'secret-password',input:{token:'secret-token'}}}),'APPROVE',diagnostics),e=>e.safeCode==='PRODUCT_APPROVE_HTTP_503');assert.deepEqual(diagnostics,[{action:'APPROVE',http_status:503,detail_code:'SERVICE_UNAVAILABLE'}]);assert(!JSON.stringify(diagnostics).includes('secret'));});
test('approval409 exposes conflict but never raw diagnostic fields',async()=>{const diagnostics=[];await assert.rejects(requireProductResponse(response(409,{detail:{code:'VERSION_CONFLICT',message:'private'}}),'APPROVE',diagnostics),e=>e.safeCode==='PRODUCT_APPROVE_HTTP_409');assert.deepEqual(diagnostics,[{action:'APPROVE',http_status:409,detail_code:'VERSION_CONFLICT'}]);});
test('approval200 returns response for subsequent active-state confirmation',async()=>{const diagnostics=[],r=response(200,{status:'approved',private:'not-logged'});assert.equal(await requireProductResponse(r,'APPROVE',diagnostics),r);assert.deepEqual(diagnostics,[{action:'APPROVE',http_status:200,detail_code:null}]);});
test('unrecognized codes are redacted even if shaped like error names',async()=>{const diagnostics=[];await assert.rejects(requireProductResponse(response(503,{detail:{code:'SECRET_TOKEN_VALUE'}}),'APPROVE',diagnostics));assert.equal(diagnostics[0].detail_code,'UNRECOGNIZED_PRODUCT_ERROR');});
test('sanitized response progress is emitted before a product failure is raised',async()=>{const diagnostics=[];let observed;Object.defineProperty(diagnostics,'onRecord',{value:()=>{observed=JSON.parse(JSON.stringify(diagnostics))}});await assert.rejects(requireProductResponse(response(503,{detail:{code:'SERVICE_UNAVAILABLE',token:'private'}}),'EXPORT',diagnostics));assert.deepEqual(observed,[{action:'EXPORT',http_status:503,detail_code:'SERVICE_UNAVAILABLE'}]);});
