'use strict';
// Layout regression only: synthetic evidence, actual frontend rendering and actions.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('../../tools/web/node_modules/playwright');
const ROOT=path.resolve(__dirname,'../..'),out=path.join(ROOT,'ops/runtime/demo/draft-layout-20260922');
fs.mkdirSync(out,{recursive:true});
const appCode=fs.readFileSync(path.join(ROOT,'frontend/app.js'),'utf8').replace(/initialize\(\);\s*$/,'');
const refs=Array.from({length:120},(_,i)=>({document_id:`evidence-${i}`,filename:`과거프로젝트_계약조건_정정서_매우_긴_문서명_${i}.pdf`,locator:`page ${i+1} / table 4 / row ${i+2}`,block_id:`block-${i}`}));
const row={title:'계약 통지 기한',current:'신규 계약의 14 calendar days 조건을 확인합니다.',past:'과거 프로젝트 통지 누락 사례와 비교',differences:'계약 및 정정서의 유효 개정 차이',decision:'REVIEW_REQUIRED',rationale:'적용 범위와 근거 검토 필요',missing_information:'승인된 공기 영향',severity:'',mitigation:'통지 기한 관리',source_refs:refs,current_refs:refs.slice(0,60),historical_refs:refs.slice(60)};
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/styles.css"><title>RE:Build Agent · 초안 표 회귀 검증</title><div id="app" class="app-layout" style="display:block"><main class="main" id="main"></main></div><div id="modal-root"></div><div id="toast" hidden></div><script>${appCode}</script><script>window.renderFixture=kind=>{state.templates=[];state.currentDraft={kind,status:'draft',revision:1,rows:Array.from({length:kind==='slides'?5:3},()=>(${JSON.stringify(row)}))};state.draftDirty=false;document.querySelector('#main').innerHTML=draftMarkup(state.currentDraft)};</script></html>`;
const server=http.createServer((req,res)=>{if(req.url==='/styles.css'){res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(path.join(ROOT,'frontend/styles.css')))}else if(req.url?.startsWith('/assets/')){res.statusCode=404;res.end()}else{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)}});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:false}),checks=[];try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto(`http://127.0.0.1:${server.address().port}`);for(const kind of ['itb','risk','slides']){await page.evaluate(kind=>window.renderFixture(kind),kind);assert.equal(await page.locator('#draft-form [data-action="source-original"]').count(),0);assert.match(await page.locator('[data-action="draft-evidence"]').first().innerText(),/120/);const metrics=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth,row:document.querySelector('tr[data-row]').getBoundingClientRect().height,cols:[...document.querySelectorAll('tr[data-row] td')].map(x=>x.getBoundingClientRect().width)}));assert(metrics.body<=metrics.viewport,JSON.stringify(metrics));assert(metrics.row<350,JSON.stringify(metrics));assert(metrics.cols.every(w=>w>=90),JSON.stringify(metrics));if(kind==='itb')await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.locator('[data-action="draft-evidence"]').first().click();assert.equal(await page.locator('.modal [data-action="source-original"]').count(),120);assert.equal(await page.locator('.modal [data-id="evidence-119"]').count(),1);assert.match(await page.locator('.modal').innerText(),/신규 프로젝트 근거 · 60개/);assert.match(await page.locator('.modal').innerText(),/과거 프로젝트 근거 · 60개/);if(kind==='itb')await page.screenshot({path:path.join(out,'evidence-dialog.png')});await page.keyboard.press('Escape');assert.equal(await page.locator('.modal').count(),0);checks.push({kind,refs:120,collapsed_row_height:metrics.row,source_links_preserved:true});}await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.renderFixture('itb'));const mobile=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth,table:document.querySelector('.draft-table-wrap').scrollWidth,container:document.querySelector('.draft-table-wrap').clientWidth}));assert(mobile.body<=mobile.viewport,JSON.stringify(mobile));assert(mobile.table>mobile.container);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});const report={product:'RE:Build Agent',status:'PASSED',boundary:'SYNTHETIC_LAYOUT_ONLY',checks,mobile,at:new Date().toISOString()};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close()}})().catch(error=>{console.error(error);server.close();process.exitCode=1});
