'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('frontend/app.js','utf8').replace(/initialize\(\);\s*$/,'')+'\nglobalThis.test={state,renderPage,renderProjects,renderKnowledge};';
const response=payload=>({ok:true,status:200,headers:{get:()=> 'application/json'},json:async()=>payload,text:async()=>JSON.stringify(payload)});
function harness(){const listeners={},nodes={'#main':{innerHTML:''},'#app':{setAttribute(){},innerHTML:''},'#modal-root':{innerHTML:'',querySelector(){return null}},'#toast':{},'#approval-check':{checked:true},'#draft-region':{innerHTML:''},'#download-status':{innerHTML:'',textContent:''}};const document={querySelector:s=>nodes[s]||null,querySelectorAll:()=>[],addEventListener:(k,v)=>listeners[k]=v,createElement:()=>({click(){},remove(){}}),body:{append(){}}};const context={document,sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},location:{hash:''},window:{addEventListener(){}},Headers,FormData,Event,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},setTimeout(){},clearTimeout(){},console,fetch:async()=>response([])};vm.createContext(context);vm.runInContext(source,context);return{context,listeners,nodes,test:context.test}}
function click(listeners,b){return listeners.click({target:{closest:()=>b}})}
async function responseOnly(){const h=harness(),requests=[];h.test.state.project={id:'p'};h.test.state.page='project';h.test.state.currentDraft={id:'d',project_id:'p',kind:'itb',rows:[],revision:1,status:'draft'};h.context.fetch=async(url,options={})=>{requests.push(url);return response(url.includes('/approve')?{...h.test.state.currentDraft,status:'approved'}:url==='/api/projects/p'?{id:'p',name:'P'}:[])};await click(h.listeners,{dataset:{action:'confirm-approval'}});assert.deepEqual(requests,['/api/drafts/d/approve'],'approval response must update draft without refetching all project data');assert.match(h.nodes['#draft-region'].innerHTML,/최종 승인/)}
async function managementOnce(){const h=harness(),requests=[];h.test.state.page='management';h.context.fetch=async url=>{requests.push(url);return response(url==='/api/management'?{projects:[],documents:[],counts:{}}:[])};await h.test.renderPage(0);assert.equal(requests.filter(x=>x==='/api/management').length,1,'management must not repeat a potentially slow full inventory fetch')}
async function pendingExport(){const h=harness(),requests=[];let done;const pending=new Promise(r=>done=r);h.test.state.project={id:'p'};h.test.state.currentDraft={id:'d',kind:'itb',status:'approved'};h.context.fetch=async url=>{requests.push(url);return pending};const b={dataset:{action:'export-draft'},disabled:false,textContent:'실제 파일 내보내기'};const first=click(h.listeners,b);assert.equal(b.disabled,true,'prevent duplicate exports while file is being built');await click(h.listeners,b);assert.equal(requests.length,1);done({ok:true,status:200,headers:{get:n=>n==='content-disposition'?'attachment; filename="result.xlsx"':'application/octet-stream'},blob:async()=>({})});await first;assert.equal(b.disabled,false);assert.match(h.nodes['#download-status'].innerHTML,/blob:test/);assert.match(h.nodes['#download-status'].innerHTML,/다운로드/)}
async function staleProject(){const h=harness();let done;const pending=new Promise(r=>done=r);h.test.state.project={id:'old'};h.test.state.page='project';h.test.state.renderGeneration=1;h.context.fetch=async url=>url==='/api/projects/old'?pending:response([]);const loading=h.test.renderProjects(1);h.test.state.project={id:'new'};h.test.state.renderGeneration=2;done(response({id:'old',name:'Old'}));await loading;assert.equal(h.test.state.project.id,'new','late page response must not overwrite current project')}
async function searchDoesNotWaitForModelStatus(){const h=harness(),requests=[];h.test.state.project={id:'p'};h.test.state.mode='search';h.test.state.page='knowledge';h.context.fetch=async url=>{requests.push(url);return response({})};await h.test.renderKnowledge(0);assert.equal(requests.length,0,'Search Mode must not wait for unrelated model login checks')}
async function managementUsesTotalCount(){for(const total of [31,0,undefined]){const h=harness();h.test.state.page='management';const newDocuments=Array.from({length:30},(_,i)=>({filename:`Document ${i}`}));h.context.fetch=async url=>response(url==='/api/management'?{projects:[],documents:[],new_documents:newDocuments,...(total===undefined?{}:{new_document_count:total})}:[]);await h.test.renderPage(0);assert.match(h.nodes['#main'].innerHTML,new RegExp('새로 유입된 문서</span><strong>'+String(total??30)+'</strong>'),'total count must not be truncated to recent-list length or replace valid zero')}}
(async()=>{for(const test of [responseOnly,managementOnce,managementUsesTotalCount,pendingExport,staleProject,searchDoesNotWaitForModelStatus])await test();console.log('frontend latency/download: 6 passed')})().catch(e=>{console.error(e);process.exitCode=1});
